// Chaque catégorie contient un id, un nom affiché, et une liste de réponses valides.
// Chaque réponse a un mot principal, des alias optionnels (variantes acceptées) et une difficulté.
// difficulty: "easy" (1 pt), "medium" (2 pts), "hard" (3 pts)

function w(word, difficulty, aliases = []) {
  return { word, difficulty, aliases };
}

export const CATEGORIES = [  
  {
    id: "clubs_ligue_1",
    name: "Clubs de football de Ligue 1",
    answers: [
      w("psg", "easy", ["paris saint-germain", "paris sg", "paris"]),
      w("om", "easy", ["olympique de marseille", "marseille"]),
      w("ol", "easy", ["olympique lyonnais", "lyon"]),
      w("as monaco", "easy", ["monaco", "asm"]),
      w("losc", "easy", ["lille", "lille osc"]),
      w("rc lens", "easy", ["lens"]),
      w("stade rennais", "easy", ["rennes", "srfc"]),
      w("ogc nice", "easy", ["nice"]),
      w("stade de reims", "medium", ["reims"]),
      w("rc strasbourg", "medium", ["strasbourg", "rcsa"]),
      w("montpellier", "medium", ["mhsc", "montpellier hsc"]),
      w("fc nantes", "easy", ["nantes"]),
      w("toulouse fc", "medium", ["toulouse", "tfc"]),
      w("stade brestois", "medium", ["brest", "sb29"]),
      w("le havre", "hard", ["hac", "le havre ac"]),
      w("auxerre", "medium", ["aja", "aj auxerre"]),
      w("angers", "hard", ["sco", "angers sco"]),
      w("saint-etienne", "easy", ["asse", "saint etienne"]),
      w("metz", "medium", ["fc metz"]),
      w("lorient", "medium", ["fc lorient"]),
      w("clermont", "hard", ["clermont foot"]),
      w("troyes", "hard", ["estac"]),
      w("bordeaux", "easy", ["girondins de bordeaux"]),
      w("ajaccio", "hard", ["aca", "ac ajaccio"]),
      w("dijon", "hard", ["dfco"]),
      w("nimes", "hard", ["nimes olympique"]),
      w("caen", "medium", ["sm caen"]),
      w("guingamp", "medium", ["eag", "en avant guingamp"]),
      w("amiens", "hard", ["amiens sc"]),
      w("angers", "hard"),
      w("sochaux", "medium", ["fcsm"]),
      w("valenciennes", "hard", ["vafc"]),
      w("nancy", "hard", ["asnl"]),
      w("bastia", "hard", ["sc bastia"]),
      w("evian", "hard", ["etg"]),
      w("sedan", "hard"),
      w("le mans", "hard")
    ],
  },
    {
    id: "instruments_musique",
    name: "Instruments de musique",
    answers: [
      w("piano", "easy", ["clavier"]),
      w("guitare", "easy", ["guitare acoustique", "gratte"]),
      w("guitare electrique", "easy"),
      w("batterie", "easy"),
      w("violon", "easy"),
      w("flute", "easy", ["flute a bec"]),
      w("flute traversiere", "medium"),
      w("trompette", "easy"),
      w("saxophone", "easy", ["sax"]),
      w("clarinette", "medium"),
      w("violoncelle", "medium"),
      w("contrebasse", "medium"),
      w("harpe", "easy"),
      w("accordeon", "easy"),
      w("ukulele", "easy"),
      w("triangle", "easy"),
      w("xylophone", "easy", ["xylo"]),
      w("maracas", "easy"),
      w("tambour", "easy", ["caisse claire"]),
      w("tambourin", "easy"),
      w("cymbales", "medium"),
      w("gong", "easy"),
      w("orgue", "medium"),
      w("harmonica", "easy"),
      w("cornemuse", "easy"),
      w("djembe", "medium"),
      w("didgeridoo", "hard"),
      w("theremine", "hard"),
      w("banjo", "medium"),
      w("mandoline", "hard"),
      w("hautbois", "hard"),
      w("basson", "hard"),
      w("tuba", "medium"),
      w("trombone", "medium"),
      w("synthetiseur", "medium", ["synthé"])
    ],
  },
  {
    id: "metiers",
    name: "Métiers et professions",
    answers: [
      w("medecin", "easy", ["docteur", "generaliste"]),
      w("pompier", "easy", ["sapeur pompier"]),
      w("policier", "easy", ["flic", "police", "gardien de la paix"]),
      w("gendarme", "easy"),
      w("enseignant", "easy", ["professeur", "prof", "instituteur", "instit", "institutrice"]),
      w("boulanger", "easy", ["boulangere"]),
      w("patissier", "easy", ["patissiere"]),
      w("boucher", "easy", ["bouchere"]),
      w("cuisinier", "easy", ["chef", "cuisiniere"]),
      w("serveur", "easy", ["serveuse"]),
      w("avocat", "easy", ["avocate"]),
      w("juge", "medium", ["magistrat"]),
      w("infirmier", "easy", ["infirmiere"]),
      w("pharmacien", "easy", ["pharmacienne"]),
      w("dentiste", "easy", ["chirurgien dentiste"]),
      w("veterinaire", "easy", ["veto"]),
      w("osteopathe", "medium", ["osteo"]),
      w("orthoptiste", "hard"),
      w("orthophoniste", "medium"),
      w("kinesitherapeute", "medium", ["kine"]),
      w("opticien", "medium", ["opticiens", "opticienne"]),
      w("pompiste", "medium"),
      w("mecanicien", "easy", ["mecanicienne", "mecano"]),
      w("electricien", "easy", ["electricienne"]),
      w("plombier", "easy"),
      w("macon", "easy", ["maconne"]),
      w("charpentier", "medium"),
      w("peintre", "easy", ["peintre en batiment"]),
      w("architecte", "easy"),
      w("ingenieur", "easy", ["ingenieure"]),
      w("informaticien", "easy", ["developpeur", "dev", "programmeur", "codeur"]),
      w("comptable", "easy"),
      w("secretaire", "easy", ["assistant", "assistante", "assistant de direction"]),
      w("journaliste", "easy"),
      w("photographe", "easy"),
      w("acteur", "easy", ["comedien", "actrice", "comedienne"]),
      w("chanteur", "easy", ["artiste", "chanteuse"]),
      w("musicien", "easy", ["musicienne"]),
      w("ecrivain", "easy", ["auteur", "autrice"]),
      w("coiffeur", "easy", ["coiffeuse"]),
      w("estheticienne", "medium", ["estheticien"]),
      w("chauffeur", "easy", ["chauffeur de taxi", "taxi", "chauffeur uber", "routier"]),
      w("pilote", "easy", ["pilote de ligne", "aviateur"]),
      w("astronaute", "easy", ["spationaute", "cosmonaute", "thomas pesquet"]),
      w("agriculteur", "easy", ["fermier", "paysan", "agricultrice"]),
      w("jardinier", "easy", ["paysagiste", "jardiniere"]),
      w("facteur", "easy", ["factrice"]),
      w("caissier", "easy", ["caissiere", "hote de caisse"]),
      w("vendeur", "easy", ["vendeuse"]),
      w("mannequin", "medium", ["modele"]),
      w("psychologue", "medium", ["psy", "psychologue"]),
      w("chirurgien", "medium", ["chirurgienne"]),
      w("poissonnier", "medium", ["poissonniere"]),
      w("fleuriste", "easy"),
      w("libraire", "easy"),
      w("notaire", "medium"),
      w("huissier", "medium", ["commissaire de justice"]),
      w("dgse", "hard", ["espion", "agent secret"]),
      w("militaire", "easy", ["soldat", "armee"]),
      w("animateur", "easy", ["animatrice", "presentateur"]),
      w("dessinateur", "easy", ["illustrateur", "graphiste"]),
      w("comique", "easy", ["humoriste"]),
      w("realisateur", "medium", ["cineaste"]),
      w("barman", "easy", ["barmaid"]),
      w("vigile", "easy", ["agent de securite"]),
      w("concierge", "medium", ["gardien d immeuble", "gardien"]),
      w("sage femme", "medium", ["maieuticien"]),
      w("assureur", "medium", ["courtier"]),
      w("banquier", "easy", ["banquiere"]),
      w("agent immobilier", "easy", ["immobilier"]),
      w("traducteur", "medium", ["traductrice"]),
      w("guide touristique", "medium", ["guide"]),
      w("archeologue", "medium"),
      w("astronome", "hard", ["astrophysicien"]),
      w("aviculteur", "hard", ["eleveur"]),
      w("bijoutier", "medium", ["joaillier"]),
      w("couturier", "easy", ["couturiere", "styliste"]),
      w("ebeniste", "hard", ["menuisier"]),
      w("serrurier", "medium"),
      w("vitrier", "hard"),
      w("bûcheron", "medium", ["bucheron"]),
      w("conducteur de travaux", "hard"),
      w("grutier", "hard"),
      w("docker", "hard"),
      w("marin", "easy", ["matelot", "navigateur"]),
      w("eboueur", "easy", ["ripeur", "macho"]),
      w("gardien de prison", "medium", ["surveillant penitentiaire"]),
      w("douanier", "medium"),
      w("diplomate", "hard", ["ambassadeur"]),
      w("homme politique", "easy", ["depute", "maire", "ministre"]),
      w("meteorologue", "hard", ["presentateur meteo"]),
      w("webmaster", "medium", ["community manager", "cm"]),
      w("data scientist", "hard"),
      w("influenceur", "easy", ["youtubeur", "streameur"]),
      w("chasseur", "easy"),
      w("pecheur", "easy"),
      w("palfrenier", "hard"),
      w("assistant maternel", "easy", ["nounou", "assmat", "baby sitter"]),
      w("atsem", "medium")
    ],
  },
  {
    id: "michael_jackson",
    name: "Titres de Michael Jackson",
    answers: [
      w("thriller", "easy"),
      w("billie jean", "easy"),
      w("beat it", "easy"),
      w("bad", "easy"),
      w("smooth criminal", "easy"),
      w("black or white", "easy", ["black and white"]),
      w("man in the mirror", "medium"),
      w("don t stop til you get enough", "medium", ["dont stop til you get enough"]),
      w("rock with you", "medium"),
      w("the way you make me feel", "medium"),
      w("earth song", "easy"),
      w("heal the world", "easy"),
      w("they don t care about us", "easy", ["they dont care about us"]),
      w("remember the time", "medium"),
      w("you are not alone", "medium"),
      w("ben", "hard"),
      w("dirty diana", "medium"),
      w("wanna be startin somethin", "hard"),
      w("human nature", "medium"),
      w("off the wall", "medium"),
      w("blood on the dance floor", "medium"),
      w("scream", "hard"),
      w("love never felt so good", "medium"),
      w("we are the world", "easy", ["usa for africa"]),
      w("say say say", "hard"),
      w("will you be there", "hard")
    ],
  },

  {
    id: "boissons",
    name: "Boissons et alcools",
    answers: [
      w("eau", "easy", ["eau minerale", "eau de source"]),
      w("eau gazeuse", "easy", ["eau petillante"]),
      w("coca", "easy", ["coca cola", "coke"]),
      w("fanta", "easy"),
      w("sprite", "easy"),
      w("orangina", "easy"),
      w("ice tea", "easy", ["lipton ice tea", "the glace"]),
      w("oasis", "easy"),
      w("jus d orange", "easy", ["jus d orange", "jus de fruit"]),
      w("jus de pomme", "easy"),
      w("jus de tomate", "medium"),
      w("lait", "easy"),
      w("cafe", "easy", ["espresso", "expresso"]),
      w("the", "easy"),
      w("tisane", "medium", ["infusion"]),
      w("chocolat chaud", "easy", ["chocolat"]),
      w("biere", "easy", ["mousse", "blonde", "brune"]),
      w("vin", "easy", ["vin rouge", "vin blanc", "rose"]),
      w("champagne", "easy", ["champ", "mousseux"]),
      w("vodka", "easy"),
      w("rhum", "easy"),
      w("whisky", "easy", ["whiskey", "bourbon"]),
      w("gin", "easy"),
      w("tequila", "easy"),
      w("mojito", "easy"),
      w("spritz", "easy"),
      w("pina colada", "medium"),
      w("margarita", "medium"),
      w("red bull", "easy", ["energy drink"]),
      w("monster", "easy"),
      w("schweppes", "easy", ["tonic"]),
      w("perrier", "easy"),
      w("ricard", "easy", ["pastis", "pasti", "51"]),
      w("martini", "medium"),
      w("malibu", "medium"),
      w("baileys", "medium"),
      w("cidre", "easy"),
      w("limonade", "easy"),
      w("sirop", "easy", ["grenadine", "sirop de menthe"]),
      w("kombucha", "hard"),
      w("bubble tea", "medium", ["the aux perles"])
    ],
  },

  {
    id: "personnages_disney",
    name: "Personnages Disney",
    answers: [
      w("mickey", "easy", ["mickey mouse"]),
      w("minnie", "easy", ["minnie mouse"]),
      w("donald", "easy", ["donald duck"]),
      w("daisy", "easy", ["daisy duck"]),
      w("dingo", "easy", ["goofy"]),
      w("pluto", "easy"),
      w("picsou", "easy", ["scrooge mcduck", "balthazar picsou"]),
      w("riri fifi loulou", "medium", ["huey dewey louie"]),
      w("simba", "easy"),
      w("mufasa", "easy"),
      w("scar", "easy"),
      w("timon", "easy"),
      w("pumbaa", "easy", ["pumba"]),
      w("aladdin", "easy", ["aladin"]),
      w("jasmin", "easy", ["jasmine"]),
      w("genie", "easy", ["the genie"]),
      w("jafar", "easy"),
      w("ariel", "easy", ["la petite sirene"]),
      w("polochon", "medium", ["flounder"]),
      w("sebastien", "medium", ["sebastian"]),
      w("ursula", "easy"),
      w("cendrillon", "easy", ["cinderella"]),
      w("blanche neige", "easy", ["snow white"]),
      w("malefique", "easy", ["maleficent"]),
      w("aurore", "easy", ["la belle au bois dormant", "aurora"]),
      w("pocahontas", "easy"),
      w("mulan", "easy"),
      w("rapunzel", "easy", ["raiponce"]),
      w("elsa", "easy", ["la reine des neiges"]),
      w("anna", "easy"),
      w("olaf", "easy"),
      w("vaiana", "easy", ["moana"]),
      w("tarzan", "easy"),
      w("hercule", "easy", ["hercules"]),
      w("hades", "medium"),
      w("peter pan", "easy"),
      w("clochette", "easy", ["tinker bell", "fee clochette"]),
      w("capitaine crochet", "easy", ["captain hook"]),
      w("stitch", "easy", ["lilo et stitch"]),
      w("lilo", "medium"),
      w("bambi", "easy"),
      w("panpan", "medium", ["thumper"]),
      w("dumbo", "easy"),
      w("pinocchio", "easy"),
      w("jiminy cricket", "medium"),
      w("beast", "easy", ["la bete"]),
      w("belle", "easy"),
      w("gaston", "easy"),
      w("kuzco", "medium"),
      w("kronk", "medium"),
      w("balthazar", "hard"),
      w("tiana", "medium"),
      w("quasimodo", "easy", ["le bossu de notre dame"])
    ],
  },

  {
    id: "bonbons",
    name: "Bonbons et confiseries",
    answers: [
      w("fraise tagada", "easy", ["tagada", "fraise haribo"]),
      w("chamallow", "easy", ["chamallows", "guimauve", "marshmallow"]),
      w("schtroumpf", "easy", ["schtroumpfs"]),
      w("crocodile", "easy", ["croco", "crocodiles"]),
      w("hari croco", "easy", ["croco haribo"]),
      w("dragibus", "easy"),
      w("carensac", "medium", ["car en sac"]),
      w("reglisse", "easy", ["rotella", "rouleau de reglisse"]),
      w("carambar", "easy"),
      w("chupa chups", "easy", ["sucette"]),
      w("mentos", "easy"),
      w("tic tac", "easy"),
      w("skittles", "easy"),
      w("m&m s", "easy", ["mms", "mnms", "treets"]),
      w("smarties", "easy"),
      w("haribo", "easy", ["bonbon haribo"]),
      w("maoam", "medium"),
      w("krema", "easy", ["regal ad"]),
      w("michoko", "medium"),
      w("werther s original", "medium", ["werthers", "bonbon au beurre"]),
      w("tetes brulees", "easy", ["tete brulee"]),
      w("cola", "easy", ["bouteille de cola", "happy cola"]),
      w("banane", "easy", ["banane haribo"]),
      w("berlingot", "hard"),
      w("nougat", "medium"),
      w("calisson", "hard"),
      w("bêtise de cambrai", "hard", ["betise de cambrai"]),
      w("sucre dorge", "medium", ["sucre d orge"]),
      w("collier", "medium", ["collier de bonbon", "bonbon collier"]),
      w("pepito", "hard"),
      w("lutti", "medium"),
      w("langue de chat", "medium", ["langue pik", "fils acidules"])
    ],
  },

  {
    id: "jeux_de_societe",
    name: "Jeux de société connus",
    answers: [
      w("monopoly", "easy"),
      w("scrabble", "easy"),
      w("uno", "easy"),
      w("bonne paye", "easy", ["la bonne paye"]),
      w("cluedo", "easy"),
      w("trivial pursuit", "easy", ["trivial poursuite"]),
      w("pictionary", "easy"),
      w("タイムボム", "hard"), // Ignorer, variante asie
      w("risk", "easy"),
      w("catan", "medium", ["les colons de catan"]),
      w("carcassonne", "medium"),
      w("les loups garous de thiercelieux", "easy", ["loups garous", "loup garou"]),
      w("time s up", "easy", ["times up"]),
      w("blanc manger coco", "easy", ["bmc"]),
      w("cards against humanity", "medium"),
      w("dixit", "medium"),
      w("dobble", "easy"),
      w("jungle speed", "easy"),
      w("mille bornes", "easy", ["1000 bornes"]),
      w("puissance 4", "easy"),
      w("touché coulé", "easy", ["bataille navale"]),
      w("qui est ce", "easy", ["qui est-ce"]),
      w("docteur maboul", "easy"),
      w("destins", "easy", ["le jeu de la vie"]),
      w("7 wonders", "medium", ["seven wonders"]),
      w("azul", "medium"),
      w("codenames", "medium", ["code name"]),
      w("mysterium", "medium"),
      w("microcosmos", "hard"),
      w("splendor", "medium"),
      w("tarot", "easy", ["jeu de tarot"]),
      w("belote", "easy"),
      w("echecs", "easy", ["jeu d echecs"]),
      w("dames", "easy", ["jeu de dames"]),
      w("solitaire", "medium"),
      w("labirynthe", "easy", ["labyrinthe"])
    ],
  },

  {
    id: "rue_monopoly",
    name: "Rues et cases du Monopoly (France)",
    answers: [
      w("rue de la paix", "easy"),
      w("avenue des champs elysees", "easy", ["champs elysees"]),
      w("boulevard de belleville", "easy", ["belleville"]),
      w("rue de courcelles", "medium"),
      w("avenue de neuilly", "medium", ["neuilly"]),
      w("rue de vaugirard", "medium", ["vaugirard"]),
      w("rue de la fayette", "medium", ["lafayette", "rue lafayette"]),
      w("boulevard de la gare", "medium", ["gare"]),
      w("avenue de la republique", "medium", ["republique"]),
      w("boulevard de la villette", "easy", ["la villette"]),
      w("avenue de breteuil", "hard", ["breteuil"]),
      w("avenue foch", "medium"),
      w("boulevard des capucines", "medium", ["capucines"]),
      w("boulevard des italiens", "medium", ["italiens"]),
      w("avenue de wagram", "hard", ["wagram"]),
      w("avenue henri martin", "hard", ["henri martin"]),
      w("faubourg saint honore", "medium", ["rue du faubourg saint honore"]),
      w("place de la bourse", "medium", ["bourse"]),
      w("rue de paradis", "medium", ["paradis"]),
      w("avenue de mozart", "medium", ["mozart"]),
      w("boulevard de saint denis", "medium", ["saint denis"]),
      w("place pigalle", "easy", ["pigalle"]),
      w("gare de lyon", "easy"),
      w("gare montparnasse", "easy"),
      w("gare du nord", "easy"),
      w("gare saint lazare", "easy", ["st lazare"]),
      w("compagnie des eaux", "medium", ["service des eaux"]),
      w("compagnie d electricite", "medium", ["electricite"]),
      w("depart", "easy", ["case depart"]),
      w("prison", "easy", ["en prison", "simple visite"]),
      w("parc gratuit", "easy"),
      w("allez en prison", "easy"),
      w("caisse de communaute", "easy"),
      w("chance", "easy"),
      w("impot sur le revenu", "medium", ["impots"]),
      w("taxe de luxe", "medium")
    ],
  },
    {
    id: "matieres_scolaires",
    name: "Matières scolaires",
    answers: [
      w("mathematiques", "easy", ["maths", "math", "mathematique"]),
      w("francais", "easy"),
      w("histoire", "easy", ["histoire geographie", "histoire geo"]),
      w("geographie", "easy", ["geo"]),
      w("physique", "easy", ["physique chimie"]),
      w("chimie", "easy"),
      w("biologie", "easy", ["svt", "sciences de la vie et de la terre", "bio"]),
      w("anglais", "easy"),
      w("espagnol", "easy"),
      w("allemand", "easy"),
      w("italien", "easy"),
      w("arts plastiques", "easy", ["art plastique", "dessin", "arts decos"]),
      w("musique", "easy", ["education musicale"]),
      w("sport", "easy", ["eps", "education physique et sportive"]),
      w("philosophie", "easy", ["philo"]),
      w("technologie", "easy", ["techno"]),
      w("informatique", "medium", ["info"]),
      w("ses", "medium", ["sciences economiques et sociales", "economie", "eco"]),
      w("latin", "medium"),
      w("grec", "medium", ["grec ancien"]),
      w("emc", "medium", ["education morale et civique", "instruction civique", "civisme"]),
      w("litterature", "medium"),
      w("arts du spectacle", "hard", ["theatre", "cinema"]),
      w("sciences de l ingenieur", "hard", ["si"])
    ],
  },

  {
    id: "pokemon_1g",
    name: "Pokémon de la 1ère génération",
    answers: [
      w("pikachu", "easy"),
      w("bulbizarre", "easy"),
      w("salameche", "easy"),
      w("carapuce", "easy"),
      w("dracaufeu", "easy"),
      w("tortank", "easy"),
      w("florizarre", "easy"),
      w("mewtwo", "easy"),
      w("mew", "medium"),
      w("evoli", "easy"),
      w("ronflex", "easy"),
      w("ectoplasma", "easy"),
      w("fantominus", "medium"),
      w("spectrum", "medium"),
      w("dracolosse", "easy"),
      w("minidraco", "medium"),
      w("draco", "medium"),
      w("leviator", "easy"),
      w("magicarpe", "easy"),
      w("lokhlass", "easy"),
      w("aquali", "medium"),
      w("voltali", "medium"),
      w("pyroli", "medium"),
      w("morpheo", "hard"), // Note: Morphéo est 3G, mais souvent confondu.
      w("roucool", "easy"),
      w("roucoups", "medium"),
      w("roucarnage", "medium"),
      w("rattata", "easy"),
      w("rattatac", "medium"),
      w("piafabec", "easy"),
      w("rapasdepic", "medium"),
      w("abo", "easy"),
      w("arbok", "medium"),
      w("nidoran", "medium"),
      w("nidorino", "medium"),
      w("nidoking", "easy"),
      w("nidorina", "medium"),
      w("nidoqueen", "easy"),
      w("melofee", "medium"),
      w("melodelfe", "medium"),
      w("goupix", "easy"),
      w("feunard", "medium"),
      w("rondoudou", "easy"),
      w("grodoudou", "medium"),
      w("nosferapti", "easy"),
      w("nosferalto", "medium"),
      w("mystherbe", "easy"),
      w("ortide", "medium"),
      w("rafflesia", "medium"),
      w("paras", "easy"),
      w("parasekt", "medium"),
      w("mimitoss", "medium"),
      w("aeromite", "medium"),
      w("taupiqueur", "easy"),
      w("triopikeur", "medium"),
      w("miaouss", "easy"),
      w("persian", "medium"),
      w("psykokwak", "easy"),
      w("akwakwak", "medium"),
      w("ferosinge", "medium"),
      w("colossinge", "medium"),
      w("caninos", "easy"),
      w("arcanin", "easy"),
      w("ptitard", "easy"),
      w("tetarte", "medium"),
      w("tartard", "medium"),
      w("abra", "easy"),
      w("kadabra", "medium"),
      w("alakazam", "easy"),
      w("machoc", "easy"),
      w("machopeur", "medium"),
      w("mackogneur", "easy"),
      w("chetiflor", "easy"),
      w("boustiflor", "medium"),
      w("empiflor", "medium"),
      w("tentacool", "easy"),
      w("tentacruel", "medium"),
      w("racaillou", "easy"),
      w("gravalanch", "medium"),
      w("golem", "medium"),
      w("ponyta", "easy"),
      w("galopa", "easy"),
      w("ramoloss", "easy"),
      w("flagadoss", "easy"),
      w("coilorig", "medium", ["magneti"]),
      w("magneton", "medium"),
      w("canarticho", "medium"),
      w("doduo", "medium"),
      w("dodorio", "medium"),
      w("otaria", "easy"),
      w("lamantine", "medium"),
      w("tadmorv", "easy"),
      w("grotadmorv", "medium"),
      w("kokiyas", "medium"),
      w("krabboss", "medium", ["krabby"]),
      w("voltorbe", "easy"),
      w("electrode", "medium"),
      w("noeunoeuf", "easy"),
      w("noadkoko", "easy"),
      w("osselelet", "easy"),
      w("ossatueur", "medium"),
      w("kicklee", "medium"),
      w("tygnon", "medium"),
      w("excelangue", "medium"),
      w("smogo", "easy"),
      w("smogogo", "medium"),
      w("rhinocorn", "medium"),
      w("rhinoferos", "medium"),
      w("leveinard", "easy"),
      w("saquedeneu", "medium"),
      w("kangourex", "easy"),
      w("hypocentan", "medium", ["hypocentre", "hypocanthe"]), // Souvent mal orthographié
      w("hypocean", "medium"),
      w("poissirene", "easy"),
      w("poissoroy", "medium"),
      w("stari", "easy"),
      w("staross", "medium"),
      w("m mime", "medium", ["mr mime", "mr. mime"]),
      w("insecateur", "easy"),
      w("lipoutou", "easy"),
      w("elektek", "medium"),
      w("magmar", "medium"),
      w("scarabrute", "medium"),
      w("tauros", "medium"),
      w("locklass", "easy", ["lokhlass"]),
      w("metamorph", "easy"),
      w("amonita", "hard"),
      w("amonistar", "hard"),
      w("kabuto", "hard"),
      w("kabutops", "hard"),
      w("ptera", "easy"),
      w("artikodin", "easy"),
      w("electhor", "easy"),
      w("sulfura", "easy")
    ],
  },

  {
    id: "reseaux_sociaux",
    name: "Réseaux sociaux et applications",
    answers: [
      w("facebook", "easy", ["fb"]),
      w("instagram", "easy", ["insta", "ig"]),
      w("tiktok", "easy", ["tik tok"]),
      w("snapchat", "easy", ["snap"]),
      w("twitter", "easy", ["x"]),
      w("x", "easy", ["twitter"]),
      w("linkedin", "easy", ["linkdin"]),
      w("pinterest", "easy", ["pin"]),
      w("youtube", "easy", ["yt"]),
      w("twitch", "easy"),
      w("whatsapp", "easy", ["wa", "whats app"]),
      w("messenger", "easy"),
      w("telegram", "easy", ["tele gram"]),
      w("discord", "easy", ["dc"]),
      w("reddit", "medium"),
      w("bereal", "medium", ["be real"]),
      w("threads", "medium"),
      w("bluesky", "hard"),
      w("mastodon", "hard"),
      w("vimeo", "medium"),
      w("tumblr", "medium"),
      w("flickr", "hard"),
      w("skype", "easy"),
      w("signal", "medium"),
      w("wechat", "hard"),
      w("clubhouse", "hard")
    ],
  },

  {
    id: "villes_france",
    name: "Villes de France",
    answers: [
      w("paris", "easy"),
      w("marseille", "easy"),
      w("lyon", "easy"),
      w("toulouse", "easy"),
      w("nice", "easy"),
      w("nantes", "easy"),
      w("montpellier", "easy"),
      w("strasbourg", "easy"),
      w("bordeaux", "easy"),
      w("lille", "easy"),
      w("rennes", "easy"),
      w("reims", "easy"),
      w("le havre", "medium"),
      w("saint etienne", "easy", ["st etienne"]),
      w("toulon", "easy"),
      w("grenoble", "easy"),
      w("dijon", "easy"),
      w("angers", "easy"),
      w("nimes", "easy"),
      w("villeurbanne", "medium"),
      w("le mans", "easy"),
      w("aix en provence", "easy", ["aix"]),
      w("brest", "easy"),
      w("tours", "easy"),
      w("amiens", "easy"),
      w("limoges", "easy"),
      w("annecy", "easy"),
      w("boulogne billancourt", "hard", ["boulogne"]),
      w("perpignan", "easy"),
      w("metz", "easy"),
      w("besancon", "medium"),
      w("orleans", "easy"),
      w("rouen", "easy"),
      w("mulhouse", "medium"),
      w("caen", "easy"),
      w("nancy", "easy"),
      w("dunkerque", "medium"),
      w("poitiers", "easy"),
      w("versailles", "easy"),
      w("avignon", "easy"),
      w("pau", "medium"),
      w("calais", "medium"),
      w("la rochelle", "easy"),
      w("biarritz", "easy"),
      w("saint tropez", "easy", ["st tropez"]),
      w("bourges", "medium"),
      w("valence", "medium"),
      w("lorient", "medium"),
      w("troyes", "medium"),
      w("chambery", "medium"),
      w("niort", "hard"),
      w("beauvais", "hard"),
      w("chateauroux", "hard"),
      w("agen", "hard")
    ],
  },

  {
    id: "marques_voitures",
    name: "Marques de voitures et constructeurs",
    answers: [
      w("peugeot", "easy"),
      w("renault", "easy"),
      w("citroen", "easy"),
      w("volkswagen", "easy", ["vw", "volfswagen"]),
      w("audi", "easy"),
      w("bmw", "easy"),
      w("mercedes", "easy", ["mercedes benz"]),
      w("tesla", "easy"),
      w("toyota", "easy"),
      w("ford", "easy"),
      w("fiat", "easy"),
      w("opel", "easy"),
      w("nissan", "easy"),
      w("honda", "easy"),
      w("hyundai", "easy"),
      w("kia", "easy"),
      w("dacia", "easy"),
      w("porsche", "easy"),
      w("ferrari", "easy"),
      w("lamborghini", "easy", ["lambo"]),
      w("bugatti", "medium"),
      w("aston martin", "medium"),
      w("alfa romeo", "medium", ["alfa"]),
      w("volvo", "easy"),
      w("suzuki", "easy"),
      w("mazda", "easy"),
      w("mitsubishi", "medium"),
      w("subaru", "medium"),
      w("skoda", "easy"),
      w("seat", "easy"),
      w("cupra", "medium"),
      w("jeep", "easy"),
      w("land rover", "medium", ["rover", "range rover"]),
      w("jaguar", "easy"),
      w("maserati", "medium"),
      w("mclaren", "medium"),
      w("alpine", "medium"),
      w("lexus", "medium"),
      w("infiniti", "hard"),
      w("ds", "medium", ["ds automobiles"]),
      w("byd", "medium"),
      w("mg", "medium"),
      w("chevrolet", "easy", ["chevy"]),
      w("chrysler", "hard"),
      w("dodge", "medium"),
      w("cadillac", "medium"),
      w("bentley", "medium"),
      w("rolls royce", "medium", ["rolls"]),
      w("lancia", "hard"),
      w("lotus", "hard"),
      w("pagani", "hard"),
      w("koenigsegg", "hard")
    ],
  },

  {
    id: "monuments_celebres",
    name: "Monuments célèbres",
    answers: [
      w("tour eiffel", "easy", ["la tour eiffel"]),
      w("arc de triomphe", "easy"),
      w("louvre", "easy", ["musee du louvre", "pyramide du louvre"]),
      w("notre dame", "easy", ["notre dame de paris"]),
      w("sacre coeur", "easy", ["le sacre coeur"]),
      w("chateau de versailles", "easy", ["versailles"]),
      w("statue de la liberte", "easy", ["statue of liberty"]),
      w("empire state building", "easy", ["empire state"]),
      w("tour de pise", "easy"),
      w("colisee", "easy", ["le colisee"]),
      w("taj mahal", "easy"),
      w("grande muraille de chine", "easy", ["muraille de chine", "la grande muraille"]),
      w("pyramides de gizeh", "easy", ["pyramide de khops", "les pyramides d egypte", "pyramides d egypte"]),
      w("sphinx", "medium", ["le sphinx", "sphinx de gizeh"]),
      w("big ben", "easy", ["tour de londres"]),
      w("tower bridge", "medium"),
      w("opera de sydney", "easy", ["sydney opera house"]),
      w("christ redempteur", "easy", ["corcovado", "statue de rio"]),
      w("machu Picchu", "easy"),
      w("petra", "medium"),
      w("chichen itza", "medium", ["pyramide maya"]),
      w("sagrada familia", "easy"),
      w("acropole", "medium", ["parthenon", "acropole d athenes"]),
      w("mont saint michel", "easy", ["le mont saint michel"]),
      w("moulin rouge", "medium"),
      w("maison blanche", "easy", ["white house"]),
      w("pentagone", "medium", ["le pentagone"]),
      w("burj khalifa", "easy", ["tour de dubai"]),
      w("marina bay sands", "hard", ["hotel de singapour"]),
      w("pont du gard", "medium"),
      w("arene de nimes", "medium", ["arenes de nimes"]),
      w("viaduc de millau", "medium"),
      w("stonehenge", "medium"),
      w("porte de brandebourg", "medium"),
      w("mur de berlin", "easy"),
      w("kremlin", "medium", ["le kremlin"]),
      w("place rouge", "medium"),
      w("sainte sophie", "hard", ["hagia sophia"]),
      w("alhambras", "hard", ["l alhambra"]),
      w("mont rushmore", "easy", ["montagne des presidents"])
    ],
  },

  {
    id: "series_tv",
    name: "Séries TV populaires",
    answers: [
      w("game of thrones", "easy", ["got"]),
      w("breaking bad", "easy"),
      w("stranger things", "easy"),
      w("friends", "easy"),
      w("the walking dead", "easy", ["twd"]),
      w("la casa de papel", "easy", ["money heist"]),
      w("peaky blinders", "easy"),
      w("squid game", "easy"),
      w("the office", "easy"),
      w("grey s anatomy", "easy", ["greys anatomy"]),
      w("black mirror", "medium"),
      w("sherlock", "medium"),
      w("dr house", "easy", ["house"]),
      w("prison break", "easy"),
      w("lost", "easy", ["les disparus"]),
      w("malcolm", "easy"),
      w("the big bang theory", "easy", ["tbbt"]),
      w("how i met your mother", "easy", ["himym"]),
      w("lucifer", "easy"),
      w("elite", "easy"),
      w("narcos", "easy"),
      w("better call saul", "medium"),
      w("the crown", "medium"),
      w("succession", "medium"),
      w("euphoria", "medium"),
      w("wednesday", "easy", ["mercredi"]),
      w("the last of us", "easy", ["tlou"]),
      w("lupin", "easy"),
      w("gossip girl", "easy"),
      w("desperate housewives", "easy"),
      w("charmed", "easy"),
      w("buffy", "easy", ["buffy contre les vampires"]),
      w("the boys", "easy"),
      w("vikings", "easy"),
      w("sons of anarchy", "medium", ["soa"]),
      w("dexter", "easy"),
      w("mr robot", "medium"),
      w("true detective", "medium"),
      w("fargo", "hard"),
      w("the wire", "hard", ["sur ecoute"]),
      w("les soprano", "medium", ["the sopranos"]),
      w("mad men", "hard"),
      w("twin peaks", "hard"),
      w("westworld", "hard"),
      w("daredevil", "medium"),
      w("homeland", "medium"),
      w("24 heures chrono", "easy", ["24"]),
      w("arrow", "easy"),
      w("the flash", "easy", ["flash"]),
      w("supernatural", "medium"),
      w("suits", "easy", ["suits avocats sur mesure"]),
      w("brooklyn nine nine", "easy", ["b99", "brooklyn 99"]),
      w("modern family", "medium"),
      w("parks and recreation", "hard", ["parks & rec"]),
      w("shameless", "medium"),
      w("gandhi", "hard"),
      w("h", "easy"),
      w("kaamelott", "easy"),
      w("le flambeau", "easy", ["la flamme"]),
      w("dix pour cent", "medium"),
      w("bureau des legendes", "medium")
    ],
  },
  {
    id: "marques_vetements",
    name: "Marques de vêtements et mode",
    answers: [
      w("zara", "easy"),
      w("h&m", "easy", ["hm", "h et m"]),
      w("nike", "easy"),
      w("adidas", "easy"),
      w("lacoste", "easy"),
      w("levis", "easy", ["levi s"]),
      w("diesel", "easy"),
      w("puma", "easy"),
      w("calvin klein", "easy", ["ck"]),
      w("tommy hilfiger", "easy", ["tommy"]),
      w("ralph lauren", "easy", ["polo ralph lauren"]),
      w("hollister", "easy"),
      w("abercrombie", "medium", ["abercrombie & fitch"]),
      w("superdry", "easy"),
      w("mango", "easy"),
      w("celio", "easy"),
      w("jules", "easy"),
      w("brice", "medium"),
      w("kiabi", "easy"),
      w("gemo", "easy"),
      w("la halle", "easy"),
      w("c&a", "easy", ["ca", "c et a"]),
      w("primark", "easy"),
      w("uniqlo", "easy"),
      w("asos", "easy"),
      w("shein", "easy"),
      w("temu", "easy"),
      w("bershka", "easy"),
      w("pull&bear", "easy", ["pull and bear", "pull & bear"]),
      w("stradivarius", "medium"),
      w("pimkie", "easy"),
      w("promod", "easy"),
      w("etam", "easy"),
      w("camaieu", "easy"),
      w("kaporal", "easy"),
      w("temps des cerises", "medium", ["le temps des cerises"]),
      w("g-star", "medium", ["g star", "g-star raw"]),
      w("guess", "easy"),
      w("supreme", "easy"),
      w("stussy", "medium"),
      w("carhartt", "easy"),
      w("the north face", "easy", ["tnf"]),
      w("patagonia", "medium"),
      w("columbia", "medium"),
      w("vans", "easy"),
      w("converse", "easy"),
      w("champion", "easy"),
      w("fila", "easy"),
      w("reebok", "easy"),
      w("asics", "easy"),
      w("kappa", "easy"),
      w("under armour", "easy"),
      w("billabong", "medium"),
      w("quiksilver", "easy"),
      w("rip curl", "medium"),
      w("roxy", "medium"),
      w("oakley", "medium"),
      w("timberland", "easy"),
      w("dr martens", "easy", ["doc martens"]),
      w("clarks", "hard"),
      w("geox", "medium"),
      w("bata", "hard"),
      w("eram", "easy"),
      w("andre", "medium")
    ],
  },
  {
    id: "animaux_marins",
    name: "Animaux marins",
    answers: [
      w("requin", "easy", ["requin blanc", "requin marteau"]),
      w("dauphin", "easy"),
      w("baleine", "easy", ["baleine bleue"]),
      w("orque", "easy"),
      w("tortue marine", "easy", ["tortue de mer"]),
      w("pieuvre", "easy", ["poulpe"]),
      w("calamar", "easy", ["calmar"]),
      w("seiche", "medium"),
      w("meduse", "easy"),
      w("etoile de mer", "easy"),
      w("oursin", "easy"),
      w("crabe", "easy"),
      w("homard", "easy"),
      w("langouste", "medium"),
      w("crevette", "easy"),
      w("phoque", "easy"),
      w("morse", "medium"),
      w("otarie", "easy"),
      w("lamantin", "medium"),
      w("dugong", "hard"),
      w("narval", "medium"),
      w("beluga", "medium"),
      w("raie", "easy", ["raie manta"]),
      w("hippocampe", "easy"),
      w("poisson clown", "easy", ["nemo"]),
      w("poisson chirurgien", "medium", ["dory"]),
      w("espadon", "easy"),
      w("thon", "easy"),
      w("saumon", "easy"),
      w("sardine", "easy"),
      w("maquereau", "medium"),
      w("morue", "easy", ["cabillaud"]),
      w("sole", "medium"),
      w("raie", "easy"),
      w("bar", "medium", ["loup de mer"]),
      w("dorade", "medium"),
      w("turbot", "hard"),
      w("baudroie", "hard", ["lotte"]),
      w("anguille", "easy"),
      w("murene", "medium"),
      w("congre", "hard"),
      w("anemone de mer", "medium", ["anemone"]),
      w("corail", "easy"),
      w("eponge de mer", "medium", ["eponge"]),
      w("moule", "easy"),
      w("huitre", "easy"),
      w("coquille saint-jacques", "easy", ["saint-jacques"]),
      w("bulot", "medium"),
      w("bigorneau", "medium"),
      w("patelle", "hard", ["chapeau chinois"]),
      w("nautile", "hard"),
      w("limace de mer", "hard", ["nudibranche"]),
      w("krill", "hard")
    ],
  },
  {
    id: "pays",
    name: "Pays du monde",
    answers: [
      w("france", "easy"),
      w("espagne", "easy"),
      w("italie", "easy"),
      w("allemagne", "easy"),
      w("portugal", "easy"),
      w("belgique", "easy"),
      w("suisse", "easy"),
      w("angleterre", "easy", ["royaume-uni", "royaume uni"]),
      w("etats-unis", "easy", ["etats unis", "usa"]),
      w("canada", "easy"),
      w("mexique", "easy"),
      w("bresil", "easy"),
      w("argentine", "easy"),
      w("chine", "easy"),
      w("japon", "easy"),
      w("russie", "easy"),
      w("maroc", "easy"),
      w("algerie", "easy"),
      w("tunisie", "easy"),
      w("egypte", "easy"),
      w("grece", "medium"),
      w("turquie", "medium"),
      w("pays-bas", "medium", ["pays bas", "hollande"]),
      w("suede", "medium"),
      w("norvege", "medium"),
      w("danemark", "medium"),
      w("pologne", "medium"),
      w("autriche", "medium"),
      w("inde", "medium"),
      w("australie", "medium"),
      w("coree du sud", "medium", ["coree"]),
      w("senegal", "medium"),
      w("cote d ivoire", "medium", ["cote ivoire"]),
      w("colombie", "medium"),
      w("perou", "medium"),
      w("chili", "medium"),
      w("ukraine", "medium"),
      w("irlande", "medium"),
      w("ecosse", "medium"),
      w("croatie", "hard"),
      w("serbie", "hard"),
      w("hongrie", "hard"),
      w("roumanie", "hard"),
      w("finlande", "hard"),
      w("islande", "hard"),
      w("vietnam", "hard"),
      w("thailande", "hard"),
      w("indonesie", "hard"),
      w("nigeria", "hard"),
      w("kenya", "hard"),
      w("uruguay", "hard"),
    ],
  },
  {
    id: "animaux",
    name: "Animaux",
    answers: [
      w("chat", "easy"),
      w("chien", "easy"),
      w("lion", "easy"),
      w("tigre", "easy"),
      w("elephant", "easy"),
      w("singe", "easy"),
      w("girafe", "easy"),
      w("zebre", "easy"),
      w("ours", "easy"),
      w("cheval", "easy"),
      w("vache", "easy"),
      w("mouton", "easy"),
      w("cochon", "easy"),
      w("poule", "easy"),
      w("canard", "easy"),
      w("lapin", "easy"),
      w("souris", "easy"),
      w("renard", "easy"),
      w("loup", "easy"),
      w("serpent", "easy"),
      w("requin", "medium"),
      w("dauphin", "medium"),
      w("baleine", "medium"),
      w("crocodile", "medium"),
      w("kangourou", "medium"),
      w("panda", "medium"),
      w("hibou", "medium"),
      w("aigle", "medium"),
      w("pingouin", "medium", ["manchot"]),
      w("tortue", "medium"),
      w("ecureuil", "medium"),
      w("hippopotame", "medium"),
      w("rhinoceros", "medium"),
      w("guepard", "medium"),
      w("hyene", "medium"),
      w("chameau", "medium"),
      w("autruche", "hard"),
      w("flamand rose", "hard", ["flamant rose"]),
      w("koala", "medium"),
      w("paresseux", "hard"),
      w("scorpion", "hard"),
      w("mante religieuse", "hard"),
      w("ornithorynque", "hard"),
      w("lemurien", "hard"),
      w("vautour", "hard"),
      w("belette", "hard"),
      w("loutre", "hard"),
      w("phoque", "medium"),
      w("morse", "hard"),
      w("iguane", "hard"),
      w("meduse", "medium"),
    ],
  },
  {
    id: "films",
    name: "Films populaires",
    answers: [
      w("titanic", "easy"),
      w("avatar", "easy"),
      w("inception", "medium"),
      w("matrix", "easy"),
      w("gladiator", "medium"),
      w("jumanji", "easy"),
      w("frozen", "easy", ["la reine des neiges"]),
      w("shrek", "easy"),
      w("avengers", "easy"),
      w("batman", "easy"),
      w("superman", "easy"),
      w("spiderman", "easy", ["spider-man"]),
      w("joker", "easy"),
      w("interstellar", "medium"),
      w("gravity", "medium"),
      w("rocky", "easy"),
      w("rambo", "easy"),
      w("scarface", "medium"),
      w("psycho", "medium"),
      w("alien", "easy"),
      w("predator", "medium"),
      w("taxi", "easy"),
      w("amelie", "medium", ["le fabuleux destin d amelie poulain"]),
      w("intouchables", "easy"),
      w("le parrain", "medium", ["godfather"]),
      w("forrest gump", "medium"),
      w("pulp fiction", "medium"),
      w("star wars", "easy"),
      w("harry potter", "easy"),
      w("seigneur des anneaux", "medium", ["lord of the rings"]),
      w("jurassic park", "easy"),
      w("le roi lion", "easy", ["lion king"]),
      w("toy story", "easy"),
      w("up", "medium"),
      w("ratatouille", "easy"),
      w("wall-e", "medium", ["walle"]),
      w("dragon ball", "medium"),
      w("titanic 2", "hard"),
      w("la la land", "medium"),
      w("whiplash", "hard"),
      w("parasite", "medium"),
      w("oldboy", "hard"),
      w("le pianiste", "hard"),
      w("amadeus", "hard"),
      w("casablanca", "hard"),
      w("vertigo", "hard"),
      w("metropolis", "hard"),
      w("le voyage de chihiro", "hard", ["chihiro"]),
      w("princesse mononoke", "hard"),
      w("akira", "hard"),
      w("blade runner", "hard"),
    ],
  },
  {
    id: "sports",
    name: "Sports",
    answers: [
      w("football", "easy", ["foot"]),
      w("basketball", "easy", ["basket"]),
      w("tennis", "easy"),
      w("rugby", "easy"),
      w("natation", "easy"),
      w("athletisme", "easy"),
      w("cyclisme", "easy", ["velo"]),
      w("boxe", "easy"),
      w("judo", "easy"),
      w("golf", "easy"),
      w("ski", "easy"),
      w("volleyball", "medium", ["volley"]),
      w("handball", "medium", ["hand"]),
      w("escalade", "medium"),
      w("equitation", "medium"),
      w("aviron", "medium"),
      w("badminton", "medium"),
      w("escrime", "medium"),
      w("karate", "medium"),
      w("taekwondo", "medium"),
      w("snowboard", "medium"),
      w("surf", "easy"),
      w("plongee", "medium"),
      w("voile", "medium"),
      w("triathlon", "medium"),
      w("marathon", "medium"),
      w("patinage artistique", "hard", ["patinage"]),
      w("hockey sur glace", "hard", ["hockey"]),
      w("biathlon", "hard"),
      w("water-polo", "hard", ["water polo"]),
      w("tir a l arc", "hard", ["tir arc"]),
      w("squash", "hard"),
      w("curling", "hard"),
      w("bobsleigh", "hard"),
      w("haltérophilie", "hard", ["halterophilie"]),
      w("gymnastique", "medium"),
      w("decathlon", "hard"),
      w("pentathlon", "hard"),
      w("petanque", "medium"),
      w("rink hockey", "hard"),
      w("polo", "hard"),
      w("luge", "hard"),
      w("cricket", "medium"),
      w("baseball", "medium"),
      w("rink", "hard"),
      w("kitesurf", "hard"),
      w("paddle", "medium"),
      w("trail", "medium"),
      w("musculation", "easy"),
      w("danse sportive", "hard"),
      w("skateboard", "medium"),
    ],
  },
  {
    id: "metiers",
    name: "Métiers",
    answers: [
      w("medecin", "easy"),
      w("infirmier", "easy"),
      w("professeur", "easy", ["enseignant"]),
      w("avocat", "easy"),
      w("policier", "easy"),
      w("pompier", "easy"),
      w("boulanger", "easy"),
      w("cuisinier", "easy", ["chef"]),
      w("coiffeur", "easy"),
      w("electricien", "easy"),
      w("plombier", "easy"),
      w("menuisier", "medium"),
      w("comptable", "medium"),
      w("ingenieur", "easy"),
      w("architecte", "medium"),
      w("journaliste", "medium"),
      w("photographe", "medium"),
      w("acteur", "easy"),
      w("musicien", "easy"),
      w("chanteur", "easy"),
      w("pilote", "easy"),
      w("agriculteur", "medium", ["fermier"]),
      w("vendeur", "easy"),
      w("serveur", "easy"),
      w("informaticien", "medium", ["developpeur"]),
      w("dentiste", "medium"),
      w("veterinaire", "medium"),
      w("pharmacien", "medium"),
      w("psychologue", "medium"),
      w("traducteur", "medium"),
      w("notaire", "hard"),
      w("juge", "medium"),
      w("douanier", "hard"),
      w("facteur", "medium"),
      w("mecanicien", "medium"),
      w("couturier", "hard"),
      w("decorateur", "hard"),
      w("urbaniste", "hard"),
      w("geometre", "hard"),
      w("statisticien", "hard"),
      w("biologiste", "hard"),
      w("chimiste", "hard"),
      w("astrophysicien", "hard"),
      w("diplomate", "hard"),
      w("ambassadeur", "hard"),
      w("sage-femme", "hard", ["sage femme"]),
      w("kinesitherapeute", "hard", ["kine"]),
      w("steward", "medium", ["hotesse de l air"]),
      w("maçon", "easy", ["macon"]),
      w("peintre", "easy"),
      w("jardinier", "easy"),
    ],
  },
  {
    id: "objets",
    name: "Objets du quotidien",
    answers: [
      w("table", "easy"),
      w("chaise", "easy"),
      w("lit", "easy"),
      w("armoire", "easy"),
      w("canape", "easy"),
      w("television", "easy", ["tele", "tv"]),
      w("telephone", "easy"),
      w("ordinateur", "easy"),
      w("clavier", "medium"),
      w("souris", "medium"),
      w("lampe", "easy"),
      w("fourchette", "easy"),
      w("couteau", "easy"),
      w("cuillere", "easy"),
      w("assiette", "easy"),
      w("verre", "easy"),
      w("tasse", "easy"),
      w("frigo", "easy", ["refrigerateur"]),
      w("four", "easy"),
      w("micro-ondes", "medium", ["micro onde", "micro ondes"]),
      w("aspirateur", "medium"),
      w("balai", "easy"),
      w("serviette", "easy"),
      w("oreiller", "easy"),
      w("couverture", "easy"),
      w("parapluie", "easy"),
      w("valise", "easy"),
      w("sac a dos", "easy", ["sac dos"]),
      w("portefeuille", "medium"),
      w("cles", "easy", ["clefs"]),
      w("montre", "easy"),
      w("lunettes", "easy"),
      w("ceinture", "medium"),
      w("chaussures", "easy"),
      w("chaussettes", "medium"),
      w("miroir", "medium"),
      w("brosse a dents", "medium", ["brosse dents"]),
      w("savon", "medium"),
      w("shampoing", "medium"),
      w("serviette de bain", "hard"),
      w("rideau", "medium"),
      w("tapis", "medium"),
      w("horloge", "medium"),
      w("calculatrice", "hard"),
      w("agrafeuse", "hard"),
      w("ciseaux", "medium"),
      w("scotch", "medium", ["ruban adhesif"]),
      w("stylo", "easy"),
      w("crayon", "easy"),
      w("gomme", "medium"),
      w("classeur", "hard"),
    ],
  },
];

export function getCategoryById(id) {
  return CATEGORIES.find((c) => c.id === id) || null;
}

export function pickRandomCategories(count) {
  // Mélange de Fisher-Yates : un .sort(() => Math.random() - 0.5) est biaisé
  // et favorise les premières catégories de la liste, ce qui donnait
  // l'impression que les mêmes catégories revenaient toujours.
  const shuffled = [...CATEGORIES];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled.slice(0, count).map((c) => c.id);
}
