// Chaque catégorie contient un id, un nom affiché, et une liste de réponses valides.
// Chaque réponse a un mot principal, des alias optionnels (variantes acceptées) et une difficulté.
// difficulty: "easy" (1 pt), "medium" (2 pts), "hard" (3 pts)

function w(word, difficulty, aliases = []) {
  return { word, difficulty, aliases };
}

export const CATEGORIES = [
{
id: "pays",
name: "Pays du monde",
answers: [
w("france", "easy"),
w("espagne", "easy"),
w("italie", "easy"),
w("allemagne", "easy"),
w("portugal", "easy"),
w("belgique", "easy"),
w("suisse", "easy"),
w("angleterre", "easy", ["royaume-uni", "royaume uni"]),
w("etats-unis", "easy", ["etats unis", "usa"]),
w("canada", "easy"),
w("mexique", "easy"),
w("bresil", "easy"),
w("argentine", "easy"),
w("chine", "easy"),
w("japon", "easy"),
w("russie", "easy"),
w("maroc", "easy"),
w("algerie", "easy"),
w("tunisie", "easy"),
w("egypte", "easy"),
w("grece", "medium"),
w("turquie", "medium"),
w("pays-bas", "medium", ["pays bas", "hollande"]),
w("suede", "medium"),
w("norvege", "medium"),
w("danemark", "medium"),
w("pologne", "medium"),
w("autriche", "medium"),
w("inde", "medium"),
w("australie", "medium"),
w("coree du sud", "medium", ["coree"]),
w("senegal", "medium"),
w("cote d ivoire", "medium", ["cote ivoire"]),
w("colombie", "medium"),
w("perou", "medium"),
w("chili", "medium"),
w("ukraine", "medium"),
w("irlande", "medium"),
w("ecosse", "medium"),
w("croatie", "hard"),
w("serbie", "hard"),
w("hongrie", "hard"),
w("roumanie", "hard"),
w("finlande", "hard"),
w("islande", "hard"),
w("vietnam", "hard"),
w("thailande", "hard"),
w("indonesie", "hard"),
w("nigeria", "hard"),
w("kenya", "hard"),
w("uruguay", "hard"),
w("afghanistan", "hard"),
w("afrique du sud", "medium"),
w("albanie", "hard"),
w("andorre", "hard"),
w("angola", "hard"),
w("arabie saoudite", "medium"),
w("armenie", "hard"),
w("azerbaidjan", "hard"),
w("bahamas", "medium"),
w("bangladesh", "hard"),
w("barbade", "hard"),
w("bahrein", "hard"),
w("belize", "hard"),
w("benin", "hard"),
w("bhoutan", "hard"),
w("bielorussie", "hard"),
w("birmanie", "hard", ["myanmar"]),
w("bolivie", "medium"),
w("bosnie", "hard", ["bosnie-herzegovine"]),
w("botswana", "hard"),
w("brunei", "hard"),
w("bulgarie", "medium"),
w("burkina faso", "hard"),
w("burundi", "hard"),
w("cambodge", "medium"),
w("cameroun", "medium"),
w("cap-vert", "hard", ["cap vert"]),
w("centrafrique", "hard"),
w("chypre", "medium"),
w("comores", "hard"),
w("congo", "medium"),
w("coree du nord", "medium"),
w("costa rica", "medium"),
w("cuba", "easy"),
w("djibouti", "hard"),
w("dominique", "hard"),
w("emirats arabes unis", "medium", ["eau", "dubai"]),
w("equateur", "medium"),
w("erythree", "hard"),
w("estonie", "hard"),
w("ethiopie", "medium"),
w("fidji", "hard"),
w("gabon", "hard"),
w("gambie", "hard"),
w("georgie", "hard"),
w("ghana", "medium"),
w("guatemala", "medium"),
w("guinee", "hard"),
w("guyana", "hard"),
w("haiti", "medium"),
w("honduras", "hard"),
w("irak", "easy"),
w("iran", "easy"),
w("israel", "easy"),
w("jamaique", "easy"),
w("jordanie", "medium"),
w("kazakhstan", "medium"),
w("kirghizistan", "hard"),
w("kiribati", "hard"),
w("koweit", "hard"),
w("laos", "medium"),
w("lesotho", "hard"),
w("lettonie", "hard"),
w("liban", "medium"),
w("liberia", "hard"),
w("libye", "medium"),
w("liechtenstein", "hard"),
w("lituanie", "hard"),
w("luxembourg", "easy"),
w("macedoine du nord", "hard", ["macedoine"]),
w("madagascar", "easy"),
w("malaisie", "medium"),
w("malawi", "hard"),
w("maldives", "easy"),
w("mali", "medium"),
w("malte", "medium"),
w("maurice", "medium", ["ile maurice"]),
w("mauritanie", "hard"),
w("moldavie", "hard"),
w("monaco", "easy"),
w("mongolie", "medium"),
w("montenegro", "hard"),
w("mozambique", "hard"),
w("namibie", "hard"),
w("nauru", "hard"),
w("nepal", "medium"),
w("nicaragua", "hard"),
w("niger", "hard"),
w("nouvelle-zelande", "medium", ["nouvelle zelande"]),
w("oman", "hard"),
w("ouganda", "hard"),
w("ouzbekistan", "hard"),
w("pakistan", "medium"),
w("palaos", "hard"),
w("palestine", "medium"),
w("panama", "medium"),
w("papouasie-nouvelle-guinee", "hard", ["papouasie"]),
w("paraguay", "medium"),
w("philippines", "medium"),
w("qatar", "easy"),
w("republique dominicaine", "medium"),
w("republique tcheque", "medium", ["tchequie"]),
w("rwanda", "medium"),
w("saint-marin", "hard", ["saint marin"]),
w("salomon", "hard", ["iles salomon"]),
w("salvador", "hard"),
w("samoa", "hard"),
w("sao tome-et-principe", "hard"),
w("seychelles", "medium"),
w("sierra leone", "hard"),
w("singapour", "medium"),
w("slovaquie", "hard"),
w("slovenie", "hard"),
w("somalie", "hard"),
w("soudan", "hard"),
w("sri lanka", "medium"),
w("swaziland", "hard", ["eswatini"]),
w("syrie", "medium"),
w("tadjikistan", "hard"),
w("taiwan", "medium"),
w("tanzanie", "medium"),
w("tchad", "hard"),
w("togo", "hard"),
w("tonga", "hard"),
w("trinite-et-tobago", "hard"),
w("turkmenistan", "hard"),
w("tuvalu", "hard"),
w("vanuatu", "hard"),
w("vatican", "easy"),
w("venezuela", "medium"),
w("yemen", "hard"),
w("zambie", "hard"),
w("zimbabwe", "hard")
],
},
{
id: "animaux",
name: "Animaux",
answers: [
w("chat", "easy"),
w("chien", "easy"),
w("lion", "easy"),
w("tigre", "easy"),
w("elephant", "easy"),
w("singe", "easy"),
w("girafe", "easy"),
w("zebre", "easy"),
w("ours", "easy"),
w("cheval", "easy"),
w("vache", "easy"),
w("mouton", "easy"),
w("cochon", "easy"),
w("poule", "easy"),
w("canard", "easy"),
w("lapin", "easy"),
w("souris", "easy"),
w("renard", "easy"),
w("loup", "easy"),
w("serpent", "easy"),
w("requin", "medium"),
w("dauphin", "medium"),
w("baleine", "medium"),
w("crocodile", "medium"),
w("kangourou", "medium"),
w("panda", "medium"),
w("hibou", "medium"),
w("aigle", "medium"),
w("pingouin", "medium", ["manchot"]),
w("tortue", "medium"),
w("ecureuil", "medium"),
w("hippopotame", "medium"),
w("rhinoceros", "medium"),
w("guepard", "medium"),
w("hyene", "medium"),
w("chameau", "medium"),
w("autruche", "hard"),
w("flamand rose", "hard", ["flamant rose"]),
w("koala", "medium"),
w("paresseux", "hard"),
w("scorpion", "hard"),
w("mante religieuse", "hard"),
w("ornithorynque", "hard"),
w("lemurien", "hard"),
w("vautour", "hard"),
w("belette", "hard"),
w("loutre", "hard"),
w("phoque", "medium"),
w("morse", "hard"),
w("iguane", "hard"),
w("meduse", "medium"),
w("abeille", "easy"),
w("agneau", "easy"),
w("alligator", "medium"),
w("albatros", "hard"),
w("alpaga", "medium"),
w("ane", "easy"),
w("antilope", "medium"),
w("araignee", "easy"),
w("babouin", "medium"),
w("bison", "medium"),
w("blaireau", "medium"),
w("boa", "medium"),
w("bouc", "easy"),
w("bourdon", "medium"),
w("buffle", "medium"),
w("cafard", "easy"),
w("caille", "hard"),
w("cameleon", "medium"),
w("canari", "easy"),
w("carpe", "medium"),
w("castor", "medium"),
w("cerf", "easy"),
w("chacal", "medium"),
w("chameau", "medium"),
w("chamois", "hard"),
w("chauve-souris", "easy", ["chauve souris"]),
w("chenille", "easy"),
w("chevre", "easy"),
w("chevreuil", "medium"),
w("chimpanze", "easy"),
w("chinchilla", "medium"),
w("chouette", "easy"),
w("cigale", "medium"),
w("cigogne", "medium"),
w("coati", "hard"),
w("coq", "easy"),
w("coyote", "medium"),
w("crabe", "easy"),
w("crapaud", "easy"),
w("crevette", "easy"),
w("criquet", "medium"),
w("cygne", "easy"),
w("daim", "medium"),
w("dindon", "easy"),
w("dromadaire", "easy"),
w("elan", "medium"),
w("epervier", "hard"),
w("escargot", "easy"),
w("espadon", "medium"),
w("faisan", "hard"),
w("faon", "easy"),
w("furet", "easy"),
w("frelon", "medium"),
w("fourmi", "easy"),
w("gaspard", "hard"),
w("geai", "hard"),
w("girafe", "easy"),
w("glouton", "hard"),
w("gnou", "medium"),
w("gorille", "easy"),
w("grenouille", "easy"),
w("grive", "hard"),
w("guepe", "easy"),
w("hamster", "easy"),
w("herisson", "easy"),
w("heron", "medium"),
w("homard", "medium"),
w("ibis", "hard"),
w("jaguar", "easy"),
w("jars", "medium"),
w("langouste", "medium"),
w("lapin", "easy"),
w("lama", "easy"),
w("leopard", "easy"),
w("lepre", "hard"),
w("lezard", "easy"),
w("libellule", "medium"),
w("lievre", "easy"),
w("limaçon", "hard"),
w("limace", "easy"),
w("linx", "medium", ["lynx"]),
w("loir", "hard"),
w("lotte", "hard"),
w("luciole", "medium"),
w("macaque", "medium"),
w("marmotte", "easy"),
w("martre", "hard"),
w("merle", "easy"),
w("moustique", "easy"),
w("mouette", "easy"),
w("moule", "easy"),
w("mulet", "medium"),
w("muton", "easy"),
w("narval", "hard"),
w("oie", "easy"),
w("opossum", "medium"),
w("orque", "easy"),
w("oursin", "medium"),
w("panthere", "easy"),
w("paon", "easy"),
w("papillon", "easy"),
w("pélican", "medium"),
w("perroquet", "easy"),
w("perruche", "easy"),
w("pie", "easy"),
w("pieuvre", "easy", ["poulpe"]),
w("pigeon", "easy"),
w("pika", "hard"),
w("pinson", "hard"),
w("punaise", "easy"),
w("putois", "easy"),
w("pithon", "medium", ["python"]),
w("rat", "easy"),
w("raton laveur", "easy"),
w("raie", "medium"),
w("renard", "easy"),
w("requin", "easy"),
w("sanglier", "easy"),
w("sardine", "easy"),
w("saumon", "easy"),
w("sauterelle", "easy"),
w("seiche", "medium"),
w("singe", "easy"),
w("taupe", "easy"),
w("taureau", "easy"),
w("thon", "easy"),
w("truite", "easy"),
w("vache", "easy"),
w("ver de terre", "easy"),
w("vipere", "medium"),
w("wombat", "hard"),
w("yak", "medium")
],
},
{
id: "fruits",
name: "Fruits",
answers: [
w("pomme", "easy"),
w("poire", "easy"),
w("banane", "easy"),
w("orange", "easy"),
w("fraise", "easy"),
w("framboise", "easy"),
w("cerise", "easy"),
w("peche", "easy"),
w("abricot", "easy"),
w("raisin", "easy"),
w("ananas", "easy"),
w("mangue", "easy"),
w("citron", "easy"),
w("pamplemousse", "easy"),
w("melon", "easy"),
w("pasteque", "easy"),
w("kiwi", "easy"),
w("avocat", "easy"),
w("prune", "easy"),
w("figue", "easy"),
w("clementine", "easy"),
w("mandarine", "easy"),
w("myrtille", "medium"),
w("mure", "medium"),
w("groseille", "medium"),
w("cassis", "medium"),
w("litchi", "medium"),
w("fruit de la passion", "medium", ["passion"]),
w("grenade", "medium"),
w("papaye", "medium"),
w("goyave", "medium"),
w("noix de coco", "easy", ["coco"]),
w("chataigne", "medium"),
w("marron", "medium"),
w("noisette", "easy"),
w("noix", "easy"),
w("amande", "easy"),
w("pistache", "easy"),
w("cacahuete", "easy"),
w("datte", "medium"),
w("pruneau", "medium"),
w("mirabelle", "medium"),
w("quetsche", "hard"),
w("reine-claude", "hard"),
w("rhubarbe", "medium"),
w("coing", "hard"),
w("nefle", "hard"),
w("kaki", "medium"),
w("kumquat", "hard"),
w("citron vert", "easy", ["lime"]),
w("carambole", "hard"),
w("pitaya", "hard", ["fruit du dragon"]),
w("ramboutan", "hard"),
w("durian", "hard"),
w("mangoustan", "hard"),
w("physalis", "hard"),
w("canneberge", "hard", ["cranberry"]),
w("acerola", "hard"),
w("tamarin", "hard"),
w("bergamote", "hard"),
w("yuzu", "hard"),
w("calamondin", "hard"),
w("combava", "hard"),
w("main de bouddha", "hard"),
w("feijoa", "hard"),
w("jackfruit", "hard", ["jacque"]),
w("sapotille", "hard"),
w("cherimole", "hard"),
w("longane", "hard"),
w("arbouse", "hard"),
w("sureau", "hard"),
w("argouse", "hard"),
w("badiane", "hard")
],
},
{
id: "legumes",
name: "Légumes",
answers: [
w("carotte", "easy"),
w("pomme de terre", "easy", ["patate"]),
w("tomate", "easy"),
w("salade", "easy", ["laitue"]),
w("courgette", "easy"),
w("aubergine", "easy"),
w("poivron", "easy"),
w("oignon", "easy"),
w("ail", "easy"),
w("echalote", "easy"),
w("poireau", "easy"),
w("haricot green", "easy", ["haricot"]),
w("petit pois", "easy", ["pois"]),
w("chou", "easy"),
w("chou-fleur", "easy", ["chou fleur"]),
w("brocoli", "easy"),
w("epinard", "easy"),
w("concombre", "easy"),
w("radis", "easy"),
w("champignon", "easy"),
w("navet", "medium"),
w("carotte blanche", "hard", ["panais"]),
w("topinambour", "hard"),
w("patate douce", "easy"),
w("potiron", "easy"),
w("citrouille", "easy"),
w("potimarron", "medium"),
w("butternut", "medium"),
w("celeri", "medium"),
w("asperge", "medium"),
w("artichaut", "medium"),
w("endive", "easy"),
w("chicoree", "hard"),
w("mache", "easy"),
w("roquette", "medium"),
w("cresson", "medium"),
w("betterave", "easy"),
w("lentille", "easy"),
w("pois chiche", "easy"),
w("feve", "medium"),
w("haricot blanc", "medium"),
w("haricot rouge", "medium"),
w("mais", "easy"),
w("fenouil", "medium"),
w("blette", "hard", ["bielette"]),
w("cardon", "hard"),
w("rutabaga", "hard"),
w("crosne", "hard"),
w("salsifis", "hard"),
w("scorsonere", "hard"),
w("rhubarbe", "medium"),
w("manioc", "medium"),
w("igname", "medium"),
w("taro", "hard"),
w("bambou", "medium", ["pousse de bambou"]),
w("coeur de palmier", "medium"),
w("cornichon", "easy"),
w("chou de bruxelles", "medium"),
w("chou rouge", "medium"),
w("chou kale", "medium"),
w("chou rave", "hard"),
w("chou chinois", "medium"),
w("gingembre", "easy"),
w("raifort", "hard"),
w("wasabi", "medium"),
w("radis noir", "medium"),
w("haricot mangetout", "hard"),
w("pois gourmand", "medium")
],
},
{
id: "boissons",
name: "Boissons",
answers: [
w("eau", "easy"),
w("eau gazeuse", "easy", ["perrier", "badoit"]),
w("jus d orange", "easy", ["jus de fruits"]),
w("jus de pomme", "easy"),
w("jus de raisin", "easy"),
w("jus de tomate", "medium"),
w("coca", "easy", ["coca cola", "coca-cola"]),
w("pepsi", "easy"),
w("fanta", "easy"),
w("sprite", "easy"),
w("orangina", "easy"),
w("schweppes", "easy"),
w("ice tea", "easy", ["lipton"]),
w("oasis", "easy"),
w("red bull", "easy", ["monster"]),
w("sirop", "easy", ["grenadine", "menthe"]),
w("limonade", "easy"),
w("diabolo", "easy"),
w("lait", "easy"),
w("cafe", "easy", ["espresso"]),
w("the", "easy"),
w("the green", "easy"),
w("tisane", "easy", ["infusion"]),
w("chocolat chaud", "easy"),
w("biere", "easy"),
w("vin", "easy"),
w("vin rouge", "easy"),
w("vin blanc", "easy"),
w("vin rose", "easy"),
w("champagne", "easy"),
w("cidre", "easy"),
w("vodka", "easy"),
w("rhum", "easy"),
w("whisky", "easy"),
w("pastis", "easy", ["ricard"]),
w("gin", "easy"),
w("tequila", "easy"),
w("liqueur", "medium"),
w("cognac", "medium"),
w("armagnac", "medium"),
w("calvados", "medium"),
w("martini", "easy"),
w("mojito", "easy"),
w("spritz", "easy"),
w("pina colada", "easy"),
w("margarita", "medium"),
w("cosmopolitan", "medium"),
w("bloody mary", "medium"),
w("caipirinha", "medium"),
w("cuba libre", "medium"),
w("sangria", "easy"),
w("punch", "easy"),
w("grog", "medium"),
w("mulled wine", "medium", ["vin chaud"]),
w("smoothie", "easy"),
w("milkshake", "easy"),
w("kefir", "hard"),
w("kombucha", "hard"),
w("lassi", "hard"),
w("sake", "medium"),
w("absinthe", "hard"),
w("malibu", "easy"),
w("baileys", "easy"),
w("get 27", "easy"),
w("suze", "medium"),
w("campari", "medium"),
w("limoncello", "medium"),
w("amaretto", "medium"),
w("mezcal", "hard")
],
},
{
id: "capitales",
name: "Capitales du monde",
answers: [
w("paris", "easy"),
w("londres", "easy"),
w("madrid", "easy"),
w("rome", "easy"),
w("berlin", "easy"),
w("lisbonne", "easy"),
w("bruxelles", "easy"),
w("amsterdam", "easy"),
w("vienne", "easy"),
w("berne", "easy"),
w("washington", "easy"),
w("ottawa", "easy"),
w("tokyo", "easy"),
w("pekin", "easy", ["beijing"]),
w("moscou", "easy"),
w("rabat", "easy"),
w("alger", "easy"),
w("tunis", "easy"),
w("le caire", "easy"),
w("athenes", "easy"),
w("ancara", "easy", ["ankara"]),
w("dublin", "easy"),
w("stockholm", "medium"),
w("oslo", "medium"),
w("copenhague", "medium"),
w("helsinki", "medium"),
w("varsovie", "medium"),
w("budapest", "medium"),
w("bucarest", "medium"),
w("prague", "medium"),
w("lisbonne", "easy"),
w("reykjavik", "medium"),
w("canberra", "medium"),
w("wellington", "medium"),
w("brasilia", "easy"),
w("buenos aires", "easy"),
w("santiago", "medium"),
w("lima", "medium"),
w("bogota", "medium"),
w("caracas", "medium"),
w("mexico", "easy"),
w("havane", "easy", ["la havane"]),
w("bangkok", "easy"),
w("hanoi", "medium"),
w("jakarta", "medium"),
w("manille", "medium"),
w("seoul", "easy"),
w("new delhi", "easy"),
w("islamabad", "medium"),
w("teheran", "medium"),
w("bagdad", "easy"),
w("riyad", "medium"),
w("abu dhabi", "medium"),
w("beyrouth", "easy"),
w("damas", "medium"),
w("jerusalem", "easy"),
w("amman", "medium"),
w("mascate", "hard"),
w("doha", "easy"),
w("koweit", "hard"),
w("kaboul", "easy"),
w("dakar", "easy"),
w("abidjan", "medium", ["yamoussoukro"]),
w("yaounde", "medium"),
w("kinshasa", "medium"),
w("brazzaville", "medium"),
w("nairobi", "medium"),
w("addis-abeba", "medium"),
w("pretoria", "medium", ["le cap"]),
w("antananarivo", "medium", ["tana"]),
w("bamako", "medium"),
w("ouagadougou", "medium"),
w("conakry", "hard"),
w("luanda", "hard"),
w("tripoli", "medium"),
w("khartoum", "hard"),
w("luxembourg", "easy"),
w("monaco", "easy"),
w("vatican", "easy"),
w("andorre-la-vieille", "hard"),
w("san marino", "hard"),
w("tallinn", "hard"),
w("riga", "hard"),
w("vilnius", "hard"),
w("minsk", "hard"),
w("kiev", "easy", ["kyiv"]),
w("chisinau", "hard"),
w("sofia", "medium"),
w("belgrade", "medium"),
w("zagreb", "medium"),
w("sarajevo", "medium"),
w("skopje", "hard"),
w("tirana", "medium"),
w("bratislava", "hard"),
w("ljubljana", "hard"),
w("nicosie", "hard"),
w("tbilissi", "hard"),
w("erevan", "hard"),
w("bakou", "hard"),
w("astana", "hard"),
w("tachkent", "hard"),
w("oulan-bator", "hard"),
w("katmandou", "medium"),
w("colombo", "hard"),
w("dhaka", "hard"),
w("phnom penh", "medium"),
w("vientiane", "hard"),
w("kuala lumpur", "medium"),
w("singapour", "medium"),
w("suva", "hard"),
w("asuncion", "hard"),
w("montevideo", "medium"),
w("la paz", "medium", ["sucre"]),
w("quito", "medium"),
w("paramaribo", "hard"),
w("georgetown", "hard"),
w("kingston", "medium"),
w("nassau", "hard"),
w("port-au-prince", "medium")
],
},
{
id: "pokemon",
name: "Pokémon (1ère Génération & Célèbres)",
answers: [
w("pikachu", "easy"),
w("dracaufeu", "easy"),
w("tortank", "easy"),
w("florizarre", "easy"),
w("salameche", "easy"),
w("carapuce", "easy"),
w("bulbizarre", "easy"),
w("evoli", "easy"),
w("mewtwo", "easy"),
w("mew", "easy"),
w("ronflex", "easy"),
w("ectoplasma", "easy"),
w("dracolosse", "easy"),
w("leviator", "easy"),
w("lucario", "easy"),
w("amphinobi", "easy"),
w("arceus", "medium"),
w("lugia", "medium"),
w("ho-oh", "medium"),
w("rayquaza", "medium"),
w("mewtwo", "easy"),
w("recolte", "hard"),
w("sulfura", "medium"),
w("artikodin", "medium"),
w("elector", "medium"),
w("raichu", "easy"),
w("reptincel", "medium"),
w("carabaffe", "medium"),
w("herbizarre", "medium"),
w("roucool", "easy"),
w("roucoups", "medium"),
w("roucarnage", "medium"),
w("rattata", "easy"),
w("rattatac", "medium"),
w("piafabec", "easy"),
w("rapasdepic", "medium"),
w("abo", "easy"),
w("arbok", "medium"),
w("sandshrew", "hard", ["sabelette"]),
w("sablaireau", "medium"),
w("nidoran", "easy"),
w("nidorina", "medium"),
w("nidoqueen", "medium"),
w("nidorino", "medium"),
w("nidoking", "medium"),
w("melofee", "easy"),
w("meloelfe", "medium"),
w("goupix", "easy"),
w("feunard", "medium"),
w("rondoudou", "easy"),
w("grodoudou", "medium"),
w("nosferapti", "easy"),
w("nosferalto", "medium"),
w("mystherbe", "easy"),
w("ortide", "medium"),
w("rafflesia", "medium"),
w("paras", "easy"),
w("parasect", "medium"),
w("mimitoss", "medium"),
w("aeromite", "medium"),
w("taupiqueur", "easy"),
w("triopikeur", "medium"),
w("miaouss", "easy"),
w("persian", "medium"),
w("psykokwak", "easy"),
w("akonawak", "medium"),
w("ferosinge", "easy"),
w("colossinge", "medium"),
w("caninos", "easy"),
w("arcanin", "medium"),
w("ptitard", "easy"),
w("tetarte", "medium"),
w("tartard", "medium"),
w("abra", "easy"),
w("kadabra", "medium"),
w("alakazam", "medium"),
w("machoc", "easy"),
w("machopeur", "medium"),
w("mackogneur", "medium"),
w("chetiflor", "easy"),
w("boustiflor", "medium"),
w("empiflor", "medium"),
w("tentacool", "easy"),
w("tentacruel", "medium"),
w("racaillou", "easy"),
w("gravalanch", "medium"),
w("golem", "medium"),
w("ponyta", "easy"),
w("galopa", "medium"),
w("ramoloss", "easy"),
w("flagadoss", "medium"),
w("magneti", "easy"),
w("magneton", "medium"),
w("canarticho", "easy"),
w("doduo", "easy"),
w("dodotrio", "medium"),
w("otaria", "easy"),
w("lamantine", "medium"),
w("tadmorv", "easy"),
w("grotadmorv", "medium"),
w("kokiyas", "easy"),
w("crustabri", "medium"),
w("fantominus", "easy"),
w("spectrum", "medium"),
w("onix", "easy"),
w("sophorifik", "easy"),
w("hypnomade", "medium"),
w("krabby", "easy"),
w("krabboss", "medium"),
w("voltorbe", "easy"),
w("electrode", "medium"),
w("noeunoeuf", "easy"),
w("noadkoko", "medium"),
w("osselelet", "easy"),
w("ossatueur", "medium"),
w("kicklee", "medium"),
w("tygnon", "medium"),
w("excelangue", "medium"),
w("smogo", "easy"),
w("smogogo", "medium"),
w("rhinocorn", "easy"),
w("rhinoferos", "medium"),
w("leveinard", "easy"),
w("saquedeneu", "medium"),
w("kangourex", "medium"),
w("hypococean", "medium"),
w("hyporoi", "hard"),
w("poissirene", "easy"),
w("poissoroy", "medium"),
w("stari", "easy"),
w("staross", "medium"),
w("m. mime", "medium", ["mr mime", "mr. mime"]),
w("insecateur", "easy"),
w("lipoutou", "medium"),
w("elektek", "medium"),
w("magmar", "medium"),
w("scarabrute", "medium"),
w("tauros", "medium"),
w("magicarpe", "easy"),
w("lokhlass", "easy"),
w("metamorph", "easy"),
w("aquali", "easy"),
w("voltali", "easy"),
w("pyroli", "easy"),
w("porygon", "medium"),
w("amonita", "hard"),
w("amonistar", "hard"),
w("kabuto", "hard"),
w("kabutops", "hard"),
w("ptera", "medium"),
w("minidraco", "easy"),
w("draco", "medium"),
w("celebi", "hard")
],
},
{
id: "jeux_video",
name: "Jeux Vidéo Célèbres",
answers: [
w("minecraft", "easy"),
w("gta", "easy", ["grand theft auto", "gta v", "gta 5", "gta 6"]),
w("fortnite", "easy"),
w("fifa", "easy", ["ea sports fc", "fc 24", "fc 25"]),
w("call of duty", "easy", ["cod", "warzone"]),
w("mario", "easy", ["super mario", "mario kart", "mario bros"]),
w("zelda", "easy", ["the legend of zelda", "breath of the wild", "totk"]),
w("pokemon", "easy"),
w("league of legends", "easy", ["lol"]),
w("world of warcraft", "easy", ["wow"]),
w("counter-strike", "easy", ["cs", "csgo", "cs2"]),
w("valorant", "easy"),
w("roblox", "easy"),
w("tetris", "easy"),
w("pac-man", "easy", ["pacman"]),
w("sonic", "easy", ["sonic the hedgehog"]),
w("the witcher", "easy", ["the witcher 3", "witcher"]),
w("cyberpunk 2077", "medium", ["cyberpunk"]),
w("red dead redemption", "easy", ["rdr2", "red dead"]),
w("assassin's creed", "easy", ["assassins creed", "ac"]),
w("tomb raider", "easy", ["lara croft"]),
w("resident evil", "easy", ["re"]),
w("elden ring", "easy"),
w("dark souls", "medium"),
w("skyrim", "easy", ["the elder scrolls"]),
w("fallout", "easy"),
w("halo", "easy"),
w("overwatch", "easy"),
w("rocket league", "easy"),
w("apex legends", "easy", ["apex"]),
w("among us", "easy"),
w("animal crossing", "easy"),
w("the sims", "easy", ["les sims", "sims"]),
w("crash bandicoot", "easy"),
w("spyro", "easy"),
w("final fantasy", "easy", ["ff7", "ff"]),
w("god of war", "easy", ["gow"]),
w("uncharted", "easy"),
w("the last of us", "easy", ["tlou"]),
w("spider-man", "easy", ["spiderman"]),
w("gran turismo", "easy"),
w("forza", "easy", ["forza horizon"]),
w("need for speed", "easy", ["nfs"]),
w("street fighter", "easy"),
w("tekken", "easy"),
w("mortal kombat", "easy"),
w("super smash bros", "easy", ["smash bros", "ssb"]),
w("doom", "easy"),
w("half-life", "medium", ["half life"]),
w("portal", "easy", ["portal 2"]),
w("bioshock", "medium"),
w("mass effect", "medium"),
w("diablo", "easy", ["diablo 4"]),
w("starcraft", "medium"),
w("hearthstone", "easy"),
w("dota 2", "medium"),
w("clash royale", "easy"),
w("clash of clans", "easy"),
w("brawl stars", "easy"),
w("candy crush", "easy"),
w("subway surfers", "easy"),
w("angry birds", "easy"),
w("plants vs zombies", "easy"),
w("hades", "medium"),
w("hollow knight", "medium"),
w("stardew valley", "medium"),
w("terraria", "medium"),
w("undertale", "medium"),
w("sea of thieves", "medium"),
w("rust", "medium"),
w("ark", "medium", ["ark survival evolved"]),
w("monster hunter", "medium"),
w("civilization", "medium"),
w("age of empires", "medium", ["aoe"]),
w("total war", "hard"),
w("simcity", "medium"),
w("cities skylines", "medium"),
w("football manager", "easy", ["fm"]),
w("pubg", "easy"),
w("rainbow six siege", "easy", ["r6", "rainbow six"]),
w("splatoon", "easy"),
w("luigi's mansion", "easy", ["luigis mansion"]),
w("metroid", "medium", ["metroid dread"]),
w("rayman", "easy"),
w("ratchet and clank", "easy", ["ratchet & clank"]),
w("jak and daxter", "medium"),
w("sly cooper", "hard"),
w("metal gear solid", "medium", ["mgs"]),
w("death stranding", "medium"),
w("ghost of tsushima", "medium"),
w("bloodborne", "medium"),
w("sekiro", "medium"),
w("detroit become human", "medium", ["detroit"]),
w("heavy rain", "hard"),
w("beyond two souls", "hard"),
w("life is strange", "medium"),
w("until dawn", "medium"),
w("dead by daylight", "medium", ["dbd"]),
w("phasmophobia", "medium")
],
},
{
id: "villes_francaises",
name: "Villes de France",
answers: [
w("paris", "easy"),
w("marseille", "easy"),
w("lyon", "easy"),
w("toulouse", "easy"),
w("nice", "easy"),
w("nantes", "easy"),
w("strasbourg", "easy"),
w("montpellier", "easy"),
w("bordeaux", "easy"),
w("lille", "easy"),
w("rennes", "easy"),
w("reims", "easy"),
w("le havre", "easy"),
w("saint-etienne", "easy", ["saint etienne"]),
w("toulon", "easy"),
w("grenoble", "easy"),
w("dijon", "easy"),
w("angers", "easy"),
w("nimes", "easy"),
w("villeurbanne", "medium"),
w("le mans", "easy"),
w("aix-en-provence", "easy", ["aix"]),
w("brest", "easy"),
w("tours", "easy"),
w("amiens", "easy"),
w("limoges", "easy"),
w("annecy", "easy"),
w("boulogne-billancourt", "medium"),
w("perpignan", "easy"),
w("metz", "easy"),
w("besancon", "easy"),
w("orleans", "easy"),
w("saint-denis", "medium"),
w("rouen", "easy"),
w("mulhouse", "medium"),
w("caen", "easy"),
w("nancy", "easy"),
w("argenteuil", "hard"),
w("tourcoing", "medium"),
w("roubaix", "medium"),
w("montreuil", "hard"),
w("avignon", "easy"),
w("nanterre", "medium"),
w("poitiers", "easy"),
w("creteil", "hard"),
w("versailles", "easy"),
w("courbevoie", "hard"),
w("pau", "easy"),
w("vitry-sur-seine", "hard"),
w("asnieres-sur-seine", "hard"),
w("colombes", "hard"),
w("aulnay-sous-bois", "hard"),
w("la rochelle", "easy"),
w("rueil-malmaison", "hard"),
w("antibes", "easy"),
w("saint-maur-des-fosses", "hard"),
w("calais", "easy"),
w("champigny-sur-marne", "hard"),
w("aubervilliers", "hard"),
w("beziers", "easy"),
w("bourges", "easy"),
w("cannes", "easy"),
w("saint-nazaire", "medium"),
w("dunkerque", "easy"),
w("valence", "easy"),
w("quimper", "medium"),
w("ajaccio", "easy"),
w("bastia", "easy"),
w("troyes", "easy"),
w("lorient", "medium"),
w("vannes", "medium"),
w("chambery", "easy"),
w("niort", "medium"),
w("colmar", "medium"),
w("gravelines", "hard"),
w("saint-brieuc", "medium"),
w("blois", "medium"),
w("tarbes", "medium"),
w("albi", "easy"),
w("carcassonne", "easy"),
w("narbonne", "medium"),
w("brive-la-gaillarde", "medium", ["brive"]),
w("agen", "medium"),
w("perigueux", "hard"),
w("angouleme", "medium"),
w("laval", "medium"),
w("chartres", "medium"),
w("evreux", "hard"),
w("charleville-mezieres", "hard"),
w("chalons-en-champagne", "hard"),
w("chaumont", "hard"),
w("bar-le-duc", "hard"),
w("epinal", "hard"),
w("belfort", "medium"),
w("vesoul", "hard"),
w("mouscron", "hard"),
w("lons-le-saunier", "hard"),
w("bourg-en-bresse", "hard"),
w("macon", "medium"),
w("mende", "hard"),
w("aurillac", "hard"),
w("le puy-en-velay", "hard", ["le puy"])
],
},
{
id: "elements_chimiques",
name: "Éléments chimiques",
answers: [
w("hydrogene", "easy"),
w("helium", "easy"),
w("carbone", "easy"),
w("azote", "easy"),
w("oxygene", "easy"),
w("fluor", "easy"),
w("neon", "easy"),
w("sodium", "easy"),
w("magnesium", "easy"),
w("aluminium", "easy"),
w("silicium", "medium"),
w("phosphore", "medium"),
w("soufre", "medium"),
w("chlore", "easy"),
w("argon", "medium"),
w("potassium", "easy"),
w("calcium", "easy"),
w("titane", "easy"),
w("chrome", "medium"),
w("manganese", "medium"),
w("fer", "easy"),
w("cobalt", "medium"),
w("nickel", "easy"),
w("cuivre", "easy"),
w("zinc", "easy"),
w("arsenic", "easy"),
w("brome", "hard"),
w("krypton", "medium"),
w("argent", "easy"),
w("etain", "medium"),
w("iode", "easy"),
w("xenon", "hard"),
w("baryum", "hard"),
w("platine", "easy"),
w("or", "easy"),
w("mercure", "easy"),
w("plomb", "easy"),
w("radon", "medium"),
w("uranium", "easy"),
w("plutonium", "easy"),
w("lithium", "easy"),
w("beryllium", "hard"),
w("bore", "hard"),
w("scandium", "hard"),
w("vanadium", "hard"),
w("gallium", "hard"),
w("germanium", "hard"),
w("selenium", "hard"),
w("rubidium", "hard"),
w("strontium", "hard"),
w("yttrium", "hard"),
w("zirconium", "hard"),
w("niobium", "hard"),
w("molybdene", "hard"),
w("technetium", "hard"),
w("ruthenium", "hard"),
w("rhodium", "hard"),
w("palladium", "hard"),
w("cadmium", "hard"),
w("indium", "hard"),
w("antimoine", "hard"),
w("tellure", "hard"),
w("cesium", "hard"),
w("lanthane", "hard"),
w("cerium", "hard"),
w("neodyme", "hard"),
w("samarium", "hard"),
w("europium", "hard"),
w("gadolinium", "hard"),
w("terbium", "hard"),
w("dysprosium", "hard"),
w("holmium", "hard"),
w("erbium", "hard"),
w("thulium", "hard"),
w("ytterbium", "hard"),
w("lutetium", "hard"),
w("hafnium", "hard"),
w("tantale", "hard"),
w("tungstene", "hard"),
w("rhenium", "hard"),
w("osmium", "hard"),
w("iridium", "hard"),
w("thallium", "hard"),
w("bismuth", "hard"),
w("polonium", "hard"),
w("astate", "hard"),
w("francium", "hard"),
w("radium", "medium"),
w("actinium", "hard"),
w("thorium", "hard"),
w("protactinium", "hard"),
w("neptunium", "hard"),
w("americium", "hard"),
w("curium", "hard"),
w("berkelium", "hard"),
w("californium", "hard"),
w("einsteinium", "hard"),
w("fermium", "hard"),
w("mendelevium", "hard"),
w("nobelium", "hard"),
w("lawrencium", "hard"),
w("rutherfordium", "hard"),
w("dubnium", "hard"),
w("seaborgium", "hard"),
w("bohrium", "hard"),
w("hassium", "hard"),
w("meitnerium", "hard"),
w("darmstadtium", "hard"),
w("roentgenium", "hard"),
w("copernicium", "hard"),
w("nihonium", "hard"),
w("flerovium", "hard"),
w("moscovium", "hard"),
w("livermorium", "hard"),
w("tennesse", "hard"),
w("oganesson", "hard")
],
},
{
id: "desserts",
name: "Desserts et Pâtisseries",
answers: [
w("tarte aux pommes", "easy"),
w("fondant au chocolat", "easy", ["moelleux au chocolat"]),
w("tiramisu", "easy"),
w("mille-feuille", "easy", ["mille feuille"]),
w("eclair", "easy", ["eclair au chocolat", "eclair au cafe"]),
w("macaron", "easy"),
w("crepe", "easy"),
w("gaufre", "easy"),
w("mousse au chocolat", "easy"),
w("creme brulee", "easy"),
w("tarte au citron", "easy", ["tarte au citron meringuee"]),
w("profiteroles", "medium"),
w("paris-brest", "medium"),
w("baba au rhum", "medium"),
w("opera", "medium"),
w("saint-honore", "medium"),
w("foret-noire", "medium", ["foret noire"]),
w("tarte tatin", "easy", ["tatin"]),
w("clafoutis", "easy"),
w("crumble", "easy"),
w("brownie", "easy"),
w("cookie", "easy"),
w("muffin", "easy"),
w("cupcake", "easy"),
w("cheesecake", "easy", ["gateau au fromage"]),
w("panna cotta", "easy"),
w("creme renversee", "medium", ["creme caramel"]),
w("flan", "easy", ["flan patissier"]),
w("madeleine", "easy"),
w("financier", "medium"),
w("canele", "easy"),
w("kouign-amann", "medium", ["kouign amann"]),
w("brioche", "easy"),
w("croissant", "easy"),
w("pain au chocolat", "easy", ["chocolatine"]),
w("chausson aux pommes", "easy"),
w("galette des rois", "easy"),
w("buche de noel", "easy", ["buche"]),
w("beignet", "easy"),
w("gaufre de liege", "medium"),
w("meringue", "easy"),
w("ile flottante", "easy", ["oeufs en neige"]),
w("charlotte", "medium", ["charlotte aux fraises"]),
w("pain d epices", "easy"),
w("quatre-quarts", "easy"),
w("gateau au yaourt", "easy"),
w("panettone", "medium"),
w("stollen", "hard"),
w("baklava", "medium"),
w("churros", "easy"),
w("donut", "easy", ["beignet americain"]),
w("pancakes", "easy"),
w("savarin", "hard"),
w("tropezienne", "medium", ["tarte tropezienne"]),
w("gugelhupf", "hard", ["kougelhopf"]),
w("financier", "medium"),
w("tuile au chocolat", "hard"),
w("palmier", "easy"),
w("sacristain", "hard"),
w("biscuit de savoie", "hard"),
w("gateau basque", "medium"),
w("pithiviers", "hard"),
w("nonnette", "hard"),
w("bugne", "medium", ["oreillette"]),
w(" pets de nonne", "hard")
],
},
{
id: "instruments_musique",
name: "Instruments de musique",
answers: [
w("piano", "easy"),
w("guitare", "easy"),
w("violon", "easy"),
w("batterie", "easy"),
w("flute", "easy", ["flute a bec"]),
w("trompette", "easy"),
w("saxophone", "easy", ["sax"]),
w("clarinette", "medium"),
w("violoncelle", "medium"),
w("harpe", "easy"),
w("accordeon", "easy"),
w("synthetiseur", "easy", ["clavier"]),
w("guitare electrique", "easy"),
w("basse", "easy", ["guitare basse"]),
w("flute traversiere", "medium"),
w("hautbois", "hard"),
w("basson", "hard"),
w("cor", "hard", ["cor d harmonie"]),
w("trombone", "medium"),
w("tuba", "medium"),
w("ukulele", "easy"),
w("mandoline", "hard"),
w("banjo", "medium"),
w("harmonica", "easy"),
w("xylophone", "easy"),
w("marimba", "hard"),
w("triangle", "easy"),
w("cymbales", "easy"),
w("tambour", "easy"),
w("tam-tam", "easy"),
w("djembe", "easy"),
w("bongo", "medium"),
w("conga", "hard"),
w("maracas", "easy"),
w("tambourin", "easy"),
w("castagnettes", "medium"),
w("orgue", "medium"),
w("clavecin", "hard"),
w("cornemuse", "easy"),
w("vielle a roue", "hard"),
w("didgeridoo", "hard"),
w("theremine", "hard"),
w("balalaika", "hard"),
w("sitar", "hard"),
w("oud", "hard"),
w("bouzouki", "hard"),
w("kalimba", "medium"),
w("hang", "hard", ["handpan"]),
w("gong", "easy"),
w("glockenspiel", "hard"),
w("chimes", "hard"),
w("timbales", "medium"),
w("batterie electronique", "medium"),
w("alto", "hard"),
w("contrebasse", "medium")
],
},
{
id: "marques_auto",
name: "Marques automobiles",
answers: [
w("renault", "easy"),
w("peugeot", "easy"),
w("citroen", "easy"),
w("volkswagen", "easy", ["vw"]),
w("audi", "easy"),
w("bmw", "easy"),
w("mercedes", "easy", ["mercedes-benz"]),
w("ford", "easy"),
w("fiat", "easy"),
w("toyota", "easy"),
w("nissan", "easy"),
w("honda", "easy"),
w("hyundai", "easy"),
w("kia", "easy"),
w("tesla", "easy"),
w("ferrari", "easy"),
w("porsche", "easy"),
w("lamborghini", "easy"),
w("aston martin", "medium"),
w("bugatti", "medium"),
w("maserati", "medium"),
w("alfa romeo", "medium"),
w("lancia", "hard"),
w("opel", "easy"),
w("seat", "easy"),
w("cupra", "medium"),
w("skoda", "easy"),
w("dacia", "easy"),
w("volvo", "easy"),
w("saab", "hard"),
w("jaguar", "easy"),
w("land rover", "easy", ["range rover"]),
w("mini", "easy"),
w("jeep", "easy"),
w("chevrolet", "easy", ["chevy"]),
w("cadillac", "medium"),
w("chrysler", "medium"),
w("dodge", "medium"),
w("mazda", "easy"),
w("subaru", "medium"),
w("suzuki", "easy"),
w("mitsubishi", "easy"),
w("lexus", "medium"),
w("infiniti", "hard"),
w("acura", "hard"),
w("alpine", "medium"),
w("ds", "easy", ["ds automobiles"]),
w("lotus", "medium"),
w("mclaren", "medium"),
w("bentley", "medium"),
w("rolls-royce", "medium", ["rolls royce"]),
w("byd", "medium"),
w("mg", "easy"),
w("lynk & co", "hard"),
w("polestar", "hard"),
w("pagani", "hard"),
w("koenigsegg", "hard"),
w("wiesmann", "hard"),
w("morgan", "hard"),
w("caterham", "hard"),
w("hummer", "medium"),
w("isuzu", "hard"),
w("iveco", "medium"),
w("smart", "easy"),
w("mahindra", "hard"),
w("tata", "hard"),
w("perodua", "hard")
],
}
];
export function getCategoryById(id) {
return CATEGORIES.find((c) => c.id === id) || null;
}


export function pickRandomCategories(count) {
  const shuffled = [...CATEGORIES].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count).map((c) => c.id);
}
