// Chaque catégorie contient un id, un nom affiché, et une liste de réponses valides.
// Chaque réponse a un mot principal, des alias optionnels (variantes acceptées) et une difficulté.
// difficulty: "easy" (1 pt), "medium" (2 pts), "hard" (3 pts)

function w(word, difficulty, aliases = []) {
  return { word, difficulty, aliases };
}

export const CATEGORIES = [
  {
    id: "pays",
    name: "Pays du monde",
    answers: [
      w("france", "easy"),
      w("espagne", "easy"),
      w("italie", "easy"),
      w("allemagne", "easy"),
      w("portugal", "easy"),
      w("belgique", "easy"),
      w("suisse", "easy"),
      w("angleterre", "easy", ["royaume-uni", "royaume uni"]),
      w("etats-unis", "easy", ["etats unis", "usa"]),
      w("canada", "easy"),
      w("mexique", "easy"),
      w("bresil", "easy"),
      w("argentine", "easy"),
      w("chine", "easy"),
      w("japon", "easy"),
      w("russie", "easy"),
      w("maroc", "easy"),
      w("algerie", "easy"),
      w("tunisie", "easy"),
      w("egypte", "easy"),
      w("grece", "medium"),
      w("turquie", "medium"),
      w("pays-bas", "medium", ["pays bas", "hollande"]),
      w("suede", "medium"),
      w("norvege", "medium"),
      w("danemark", "medium"),
      w("pologne", "medium"),
      w("autriche", "medium"),
      w("inde", "medium"),
      w("australie", "medium"),
      w("coree du sud", "medium", ["coree"]),
      w("senegal", "medium"),
      w("cote d ivoire", "medium", ["cote ivoire"]),
      w("colombie", "medium"),
      w("perou", "medium"),
      w("chili", "medium"),
      w("ukraine", "medium"),
      w("irlande", "medium"),
      w("ecosse", "medium"),
      w("croatie", "hard"),
      w("serbie", "hard"),
      w("hongrie", "hard"),
      w("roumanie", "hard"),
      w("finlande", "hard"),
      w("islande", "hard"),
      w("vietnam", "hard"),
      w("thailande", "hard"),
      w("indonesie", "hard"),
      w("nigeria", "hard"),
      w("kenya", "hard"),
      w("uruguay", "hard"),
    ],
  },
  {
    id: "animaux",
    name: "Animaux",
    answers: [
      w("chat", "easy"),
      w("chien", "easy"),
      w("lion", "easy"),
      w("tigre", "easy"),
      w("elephant", "easy"),
      w("singe", "easy"),
      w("girafe", "easy"),
      w("zebre", "easy"),
      w("ours", "easy"),
      w("cheval", "easy"),
      w("vache", "easy"),
      w("mouton", "easy"),
      w("cochon", "easy"),
      w("poule", "easy"),
      w("canard", "easy"),
      w("lapin", "easy"),
      w("souris", "easy"),
      w("renard", "easy"),
      w("loup", "easy"),
      w("serpent", "easy"),
      w("requin", "medium"),
      w("dauphin", "medium"),
      w("baleine", "medium"),
      w("crocodile", "medium"),
      w("kangourou", "medium"),
      w("panda", "medium"),
      w("hibou", "medium"),
      w("aigle", "medium"),
      w("pingouin", "medium", ["manchot"]),
      w("tortue", "medium"),
      w("ecureuil", "medium"),
      w("hippopotame", "medium"),
      w("rhinoceros", "medium"),
      w("guepard", "medium"),
      w("hyene", "medium"),
      w("chameau", "medium"),
      w("autruche", "hard"),
      w("flamand rose", "hard", ["flamant rose"]),
      w("koala", "medium"),
      w("paresseux", "hard"),
      w("scorpion", "hard"),
      w("mante religieuse", "hard"),
      w("ornithorynque", "hard"),
      w("lemurien", "hard"),
      w("vautour", "hard"),
      w("belette", "hard"),
      w("loutre", "hard"),
      w("phoque", "medium"),
      w("morse", "hard"),
      w("iguane", "hard"),
      w("meduse", "medium"),
    ],
  },
  {
    id: "films",
    name: "Films populaires",
    answers: [
      w("titanic", "easy"),
      w("avatar", "easy"),
      w("inception", "medium"),
      w("matrix", "easy"),
      w("gladiator", "medium"),
      w("jumanji", "easy"),
      w("frozen", "easy", ["la reine des neiges"]),
      w("shrek", "easy"),
      w("avengers", "easy"),
      w("batman", "easy"),
      w("superman", "easy"),
      w("spiderman", "easy", ["spider-man"]),
      w("joker", "easy"),
      w("interstellar", "medium"),
      w("gravity", "medium"),
      w("rocky", "easy"),
      w("rambo", "easy"),
      w("scarface", "medium"),
      w("psycho", "medium"),
      w("alien", "easy"),
      w("predator", "medium"),
      w("taxi", "easy"),
      w("amelie", "medium", ["le fabuleux destin d amelie poulain"]),
      w("intouchables", "easy"),
      w("le parrain", "medium", ["godfather"]),
      w("forrest gump", "medium"),
      w("pulp fiction", "medium"),
      w("star wars", "easy"),
      w("harry potter", "easy"),
      w("seigneur des anneaux", "medium", ["lord of the rings"]),
      w("jurassic park", "easy"),
      w("le roi lion", "easy", ["lion king"]),
      w("toy story", "easy"),
      w("up", "medium"),
      w("ratatouille", "easy"),
      w("wall-e", "medium", ["walle"]),
      w("dragon ball", "medium"),
      w("titanic 2", "hard"),
      w("la la land", "medium"),
      w("whiplash", "hard"),
      w("parasite", "medium"),
      w("oldboy", "hard"),
      w("le pianiste", "hard"),
      w("amadeus", "hard"),
      w("casablanca", "hard"),
      w("vertigo", "hard"),
      w("metropolis", "hard"),
      w("le voyage de chihiro", "hard", ["chihiro"]),
      w("princesse mononoke", "hard"),
      w("akira", "hard"),
      w("blade runner", "hard"),
    ],
  },
  {
    id: "sports",
    name: "Sports",
    answers: [
      w("football", "easy", ["foot"]),
      w("basketball", "easy", ["basket"]),
      w("tennis", "easy"),
      w("rugby", "easy"),
      w("natation", "easy"),
      w("athletisme", "easy"),
      w("cyclisme", "easy", ["velo"]),
      w("boxe", "easy"),
      w("judo", "easy"),
      w("golf", "easy"),
      w("ski", "easy"),
      w("volleyball", "medium", ["volley"]),
      w("handball", "medium", ["hand"]),
      w("escalade", "medium"),
      w("equitation", "medium"),
      w("aviron", "medium"),
      w("badminton", "medium"),
      w("escrime", "medium"),
      w("karate", "medium"),
      w("taekwondo", "medium"),
      w("snowboard", "medium"),
      w("surf", "easy"),
      w("plongee", "medium"),
      w("voile", "medium"),
      w("triathlon", "medium"),
      w("marathon", "medium"),
      w("patinage artistique", "hard", ["patinage"]),
      w("hockey sur glace", "hard", ["hockey"]),
      w("biathlon", "hard"),
      w("water-polo", "hard", ["water polo"]),
      w("tir a l arc", "hard", ["tir arc"]),
      w("squash", "hard"),
      w("curling", "hard"),
      w("bobsleigh", "hard"),
      w("haltérophilie", "hard", ["halterophilie"]),
      w("gymnastique", "medium"),
      w("decathlon", "hard"),
      w("pentathlon", "hard"),
      w("petanque", "medium"),
      w("rink hockey", "hard"),
      w("polo", "hard"),
      w("luge", "hard"),
      w("cricket", "medium"),
      w("baseball", "medium"),
      w("rink", "hard"),
      w("kitesurf", "hard"),
      w("paddle", "medium"),
      w("trail", "medium"),
      w("musculation", "easy"),
      w("danse sportive", "hard"),
      w("skateboard", "medium"),
    ],
  },
  {
    id: "marques",
    name: "Marques connues",
    answers: [
      w("nike", "easy"),
      w("adidas", "easy"),
      w("apple", "easy"),
      w("samsung", "easy"),
      w("google", "easy"),
      w("microsoft", "easy"),
      w("amazon", "easy"),
      w("netflix", "easy"),
      w("coca-cola", "easy", ["coca cola", "coca"]),
      w("pepsi", "easy"),
      w("mcdonald's", "easy", ["mcdonalds", "mcdo"]),
      w("burger king", "easy"),
      w("zara", "easy"),
      w("h&m", "easy", ["hm"]),
      w("puma", "easy"),
      w("reebok", "medium"),
      w("ferrari", "easy"),
      w("renault", "easy"),
      w("peugeot", "easy"),
      w("citroen", "easy"),
      w("bmw", "easy"),
      w("mercedes", "easy"),
      w("audi", "easy"),
      w("toyota", "easy"),
      w("tesla", "easy"),
      w("sony", "easy"),
      w("lg", "medium"),
      w("playstation", "easy"),
      w("xbox", "easy"),
      w("nintendo", "easy"),
      w("rolex", "medium"),
      w("gucci", "medium"),
      w("chanel", "medium"),
      w("dior", "medium"),
      w("louis vuitton", "medium"),
      w("ikea", "easy"),
      w("decathlon", "easy"),
      w("carrefour", "easy"),
      w("auchan", "medium"),
      w("danone", "medium"),
      w("nestle", "medium"),
      w("loreal", "medium", ["l'oreal"]),
      w("uber", "easy"),
      w("spotify", "easy"),
      w("instagram", "easy"),
      w("twitter", "easy", ["x"]),
      w("snapchat", "easy"),
      w("tiktok", "easy"),
      w("airbnb", "medium"),
      w("paypal", "medium"),
      w("visa", "hard"),
      w("lego", "easy"),
    ],
  },
  {
    id: "metiers",
    name: "Métiers",
    answers: [
      w("medecin", "easy"),
      w("infirmier", "easy"),
      w("professeur", "easy", ["enseignant"]),
      w("avocat", "easy"),
      w("policier", "easy"),
      w("pompier", "easy"),
      w("boulanger", "easy"),
      w("cuisinier", "easy", ["chef"]),
      w("coiffeur", "easy"),
      w("electricien", "easy"),
      w("plombier", "easy"),
      w("menuisier", "medium"),
      w("comptable", "medium"),
      w("ingenieur", "easy"),
      w("architecte", "medium"),
      w("journaliste", "medium"),
      w("photographe", "medium"),
      w("acteur", "easy"),
      w("musicien", "easy"),
      w("chanteur", "easy"),
      w("pilote", "easy"),
      w("agriculteur", "medium", ["fermier"]),
      w("vendeur", "easy"),
      w("serveur", "easy"),
      w("informaticien", "medium", ["developpeur"]),
      w("dentiste", "medium"),
      w("veterinaire", "medium"),
      w("pharmacien", "medium"),
      w("psychologue", "medium"),
      w("traducteur", "medium"),
      w("notaire", "hard"),
      w("juge", "medium"),
      w("douanier", "hard"),
      w("facteur", "medium"),
      w("mecanicien", "medium"),
      w("couturier", "hard"),
      w("decorateur", "hard"),
      w("urbaniste", "hard"),
      w("geometre", "hard"),
      w("statisticien", "hard"),
      w("biologiste", "hard"),
      w("chimiste", "hard"),
      w("astrophysicien", "hard"),
      w("diplomate", "hard"),
      w("ambassadeur", "hard"),
      w("sage-femme", "hard", ["sage femme"]),
      w("kinesitherapeute", "hard", ["kine"]),
      w("steward", "medium", ["hotesse de l air"]),
      w("maçon", "easy", ["macon"]),
      w("peintre", "easy"),
      w("jardinier", "easy"),
    ],
  },
  {
    id: "objets",
    name: "Objets du quotidien",
    answers: [
      w("table", "easy"),
      w("chaise", "easy"),
      w("lit", "easy"),
      w("armoire", "easy"),
      w("canape", "easy"),
      w("television", "easy", ["tele", "tv"]),
      w("telephone", "easy"),
      w("ordinateur", "easy"),
      w("clavier", "medium"),
      w("souris", "medium"),
      w("lampe", "easy"),
      w("fourchette", "easy"),
      w("couteau", "easy"),
      w("cuillere", "easy"),
      w("assiette", "easy"),
      w("verre", "easy"),
      w("tasse", "easy"),
      w("frigo", "easy", ["refrigerateur"]),
      w("four", "easy"),
      w("micro-ondes", "medium", ["micro onde", "micro ondes"]),
      w("aspirateur", "medium"),
      w("balai", "easy"),
      w("serviette", "easy"),
      w("oreiller", "easy"),
      w("couverture", "easy"),
      w("parapluie", "easy"),
      w("valise", "easy"),
      w("sac a dos", "easy", ["sac dos"]),
      w("portefeuille", "medium"),
      w("cles", "easy", ["clefs"]),
      w("montre", "easy"),
      w("lunettes", "easy"),
      w("ceinture", "medium"),
      w("chaussures", "easy"),
      w("chaussettes", "medium"),
      w("miroir", "medium"),
      w("brosse a dents", "medium", ["brosse dents"]),
      w("savon", "medium"),
      w("shampoing", "medium"),
      w("serviette de bain", "hard"),
      w("rideau", "medium"),
      w("tapis", "medium"),
      w("horloge", "medium"),
      w("calculatrice", "hard"),
      w("agrafeuse", "hard"),
      w("ciseaux", "medium"),
      w("scotch", "medium", ["ruban adhesif"]),
      w("stylo", "easy"),
      w("crayon", "easy"),
      w("gomme", "medium"),
      w("classeur", "hard"),
    ],
  },
];

export function getCategoryById(id) {
  return CATEGORIES.find((c) => c.id === id) || null;
}

export function pickRandomCategories(count) {
  const shuffled = [...CATEGORIES].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count).map((c) => c.id);
}
